// מאגרי-שמות ומקומות לגנרטור. 🚫 בלי מותגים אמיתיים (הכרעת-ישי 29/07/2026 על נתוני-הדגמה:
// "שמות גנריים אך אמינים"), 🚫 בלי המילה "דמו" בשום שדה (אותה הכרעה ל-`demo-seed.mjs`).
// הקואורדינטות קבועות בקוד ולא גאוקוד — Nominatim חוסם User-Agent של node (מתועד ב-
// `04_hostesses/CLAUDE.md`), והמרחקים כאן נועדו רק לייצר ציוני-קרבה שונים, לא לדייק.

export const COMPANY_NAMES = {
  private_company: [
    'אלפא סיסטמס בע"מ',
    'נובה פארמה בע"מ',
    'טכנולוגיות ענן ישראל',
    'סולאר אנרג\'י בע"מ',
    'מגדלי הים התיכון',
    'קליק פינטק בע"מ',
    'ביו-לוג מעבדות',
    'רשת אופנה גל בע"מ',
    'סייבר-שילד בע"מ',
    'דלתא לוגיסטיקה',
    'אופק ביטוח ופיננסים',
    'מטריקס דאטה בע"מ',
    'פלטינום נדל"ן',
    'אורן תעשיות מזון',
    'קוואנטום רובוטיקה',
    'הדר מערכות רפואיות',
    'נטוורק פלוס בע"מ',
    'סמארט-סיטי פתרונות',
    'ירוק בעיר בע"מ',
    'אקסלנס אקדמיה',
    'טופ-ליין תקשורת',
    'קרן הצפון להשקעות',
    'ויז\'ן אופטיקה בע"מ',
    'מיטב מוצרי חשמל',
    'ספיר ייעוץ ארגוני',
    'גלובל שיפינג בע"מ',
    'אינפיניטי גיימינג',
    'ורד קוסמטיקה טבעית',
    'בנק העסקים הקטנים',
    'מוטורס ישראל בע"מ',
    'עמק חפר אגרו-טק',
    'לב הנגב תיירות',
    'שחף תעופה ואחזקה',
    'ברק שיווק דיגיטלי',
    'טל-מד שירותי בריאות',
    'זהב אנרגיה מתחדשת',
    'קמפוס הסטארטאפים',
    'ניצן הדפסות ומיתוג',
  ],
  production_company: [
    'הפקות דרור',
    'קונספט הפקות בע"מ',
    'לייב אירועים בע"מ',
    'סטודיו במה הפקות',
    'אורות הפקות אירועים',
    'פרימיום אירועים',
    'זירה הפקות',
    'מאסטר-פלאן הפקות',
    'קול ובמה בע"מ',
    'מגה-אירוע הפקות',
    'שקד הפקות כנסים',
    'אלמנט הפקות',
  ],
  government: [
    'עיריית נתניה',
    'עיריית רעננה',
    'מועצה אזורית עמק חפר',
    'עיריית כפר סבא',
    'מועצה מקומית שוהם',
    'עיריית מודיעין',
    'רשות הניקוז והנחלים',
    'המועצה הלאומית לאיכות הסביבה',
  ],
  nonprofit: [
    'עמותת יד לקשיש',
    'עמותת אור לנוער',
    'עמותת קול הלב',
    'האגודה למען המדע הצעיר',
    'עמותת צעדים ירוקים',
    'קרן שביל הזהב',
  ],
}

// סלאגים לטיניים למיילים — אחד לכל שם למעלה, באותו סדר (הכתובת נבנית מהסלאג).
export const COMPANY_SLUGS = {
  private_company: [
    'alpha-systems',
    'nova-pharma',
    'cloud-il',
    'solar-energy',
    'med-towers',
    'click-fintech',
    'biolog-labs',
    'gal-fashion',
    'cyber-shield',
    'delta-logistics',
    'ofek-insurance',
    'matrix-data',
    'platinum-re',
    'oren-foods',
    'quantum-robotics',
    'hadar-medical',
    'network-plus',
    'smart-city',
    'green-city',
    'excellence-academy',
    'topline-telecom',
    'north-fund',
    'vision-optics',
    'meitav-electric',
    'sapir-consulting',
    'global-shipping',
    'infinity-gaming',
    'vered-cosmetics',
    'smallbiz-bank',
    'motors-il',
    'hefer-agrotech',
    'negev-tourism',
    'shahaf-aviation',
    'barak-digital',
    'telmed-health',
    'zahav-energy',
    'startup-campus',
    'nitzan-print',
  ],
  production_company: [
    'dror-productions',
    'concept-prod',
    'live-events',
    'studio-bama',
    'orot-events',
    'premium-events',
    'zira-prod',
    'masterplan-prod',
    'kol-bama',
    'mega-event',
    'shaked-conf',
    'element-prod',
  ],
  government: [
    'netanya-muni',
    'raanana-muni',
    'emek-hefer',
    'kfar-saba-muni',
    'shoham-council',
    'modiin-muni',
    'drainage-authority',
    'env-council',
  ],
  nonprofit: [
    'yad-lakashish',
    'or-lanoar',
    'kol-halev',
    'young-science',
    'green-steps',
    'golden-path',
  ],
}

export const FIRST_NAMES_F = [
  'נועה',
  'שירה',
  'מאיה',
  'תמר',
  'יעל',
  'רוני',
  'הילה',
  'עדי',
  'דנה',
  'ליאור',
  'אורית',
  'מיכל',
  'שני',
  'ענבר',
  'גלי',
  'רותם',
  'אביב',
  'ניצן',
  'טליה',
  'אלה',
  'קרן',
  'סיון',
  'נטע',
  'ליהי',
  'עומר',
  'שקד',
  'יובל',
  'אגם',
  'מור',
  'רומי',
  'אופיר',
  'לירון',
  'אביגיל',
  'מעיין',
  'הדס',
  'ירדן',
  'אלמוג',
  'עלמה',
  'זוהר',
  'נופר',
]

// תעתיק לטיני של FIRST_NAMES_F — אותו סדר, לכתובות-מייל של דיילות.
export const FIRST_NAMES_F_ASCII = [
  'noa',
  'shira',
  'maya',
  'tamar',
  'yael',
  'roni',
  'hila',
  'adi',
  'dana',
  'lior',
  'orit',
  'michal',
  'shani',
  'inbar',
  'gali',
  'rotem',
  'aviv',
  'nitzan',
  'talia',
  'ella',
  'keren',
  'sivan',
  'neta',
  'lihi',
  'omer',
  'shaked',
  'yuval',
  'agam',
  'mor',
  'romi',
  'ofir',
  'liron',
  'avigail',
  'maayan',
  'hadas',
  'yarden',
  'almog',
  'alma',
  'zohar',
  'nofar',
]

export const FIRST_NAMES_M = [
  'רון',
  'טל',
  'אורי',
  'עידו',
  'יונתן',
  'עמית',
  'נדב',
  'אלון',
  'גיא',
  'איתי',
  'דניאל',
  'עופר',
  'ניר',
  'אסף',
  'שחר',
  'ליאור',
  'רועי',
  'יואב',
  'תומר',
  'ברק',
]

export const LAST_NAMES = [
  'כהן',
  'לוי',
  'מזרחי',
  'פרץ',
  'ביטון',
  'דהן',
  'אברהם',
  'פרידמן',
  'מלכה',
  'אזולאי',
  'שפירא',
  'גולן',
  'ברק',
  'אלמוג',
  'רוזן',
  'נחום',
  'הרוש',
  'אטיאס',
  'שני',
  'מור',
  'בן דוד',
  'חדד',
  'עמר',
  'אוחיון',
  'גבאי',
  'ישראלי',
  'ברקאי',
  'לוגסי',
  'רזניק',
  'אשכנזי',
  'סבן',
  'קדוש',
  'יוסף',
  'חיים',
  'שלום',
  'ניסים',
  'אלבז',
  'בוזגלו',
  "תורג'מן",
  'צור',
]

// תעתיק לטיני של LAST_NAMES — אותו סדר.
export const LAST_NAMES_ASCII = [
  'cohen',
  'levi',
  'mizrahi',
  'peretz',
  'biton',
  'dahan',
  'avraham',
  'friedman',
  'malka',
  'azulay',
  'shapira',
  'golan',
  'barak',
  'almog',
  'rozen',
  'nahum',
  'harush',
  'atias',
  'shani',
  'mor',
  'bendavid',
  'hadad',
  'amar',
  'ohayon',
  'gabay',
  'israeli',
  'barkai',
  'lugassi',
  'reznik',
  'ashkenazi',
  'saban',
  'kadosh',
  'yosef',
  'haim',
  'shalom',
  'nissim',
  'elbaz',
  'buzaglo',
  'turgeman',
  'tzur',
]

// ערים — עם קואורדינטות מקורבות של מרכז-העיר. כל דיילת מקבלת "ריצוד" קטן סביבן.
export const CITIES = [
  { name: 'תל אביב', lat: 32.0809, lng: 34.7806, weight: 10 },
  { name: 'רמת גן', lat: 32.0823, lng: 34.8138, weight: 6 },
  { name: 'גבעתיים', lat: 32.0714, lng: 34.8102, weight: 3 },
  { name: 'פתח תקווה', lat: 32.0878, lng: 34.8878, weight: 6 },
  { name: 'הרצליה', lat: 32.1663, lng: 34.8436, weight: 4 },
  { name: 'רעננה', lat: 32.1848, lng: 34.8713, weight: 3 },
  { name: 'כפר סבא', lat: 32.175, lng: 34.9068, weight: 3 },
  { name: 'הוד השרון', lat: 32.1502, lng: 34.8888, weight: 2 },
  { name: 'נתניה', lat: 32.3215, lng: 34.8532, weight: 4 },
  { name: 'חדרה', lat: 32.4341, lng: 34.9197, weight: 2 },
  { name: 'חיפה', lat: 32.794, lng: 34.9896, weight: 3 },
  { name: 'ראשון לציון', lat: 31.9642, lng: 34.8047, weight: 6 },
  { name: 'חולון', lat: 32.0158, lng: 34.7874, weight: 5 },
  { name: 'בת ים', lat: 32.0171, lng: 34.7515, weight: 3 },
  { name: 'רחובות', lat: 31.8928, lng: 34.8113, weight: 3 },
  { name: 'נס ציונה', lat: 31.9293, lng: 34.7987, weight: 2 },
  { name: 'מודיעין', lat: 31.8969, lng: 35.0104, weight: 2 },
  { name: 'ירושלים', lat: 31.7683, lng: 35.2137, weight: 3 },
  { name: 'אשדוד', lat: 31.8014, lng: 34.6435, weight: 2 },
  { name: 'לוד', lat: 31.9516, lng: 34.8956, weight: 1 },
  { name: 'רמלה', lat: 31.9293, lng: 34.8722, weight: 1 },
  { name: 'קריית אונו', lat: 32.0553, lng: 34.8559, weight: 2 },
  { name: 'יהוד', lat: 32.0334, lng: 34.8908, weight: 1 },
]

export const STREETS = [
  'הרצל',
  'ויצמן',
  'רוטשילד',
  "ז'בוטינסקי",
  'בן גוריון',
  'סוקולוב',
  'אחוזה',
  'הנשיא',
  'העצמאות',
  'הגפן',
  'התמר',
  'האלון',
  'ביאליק',
  'אבן גבירול',
  'דיזנגוף',
]

export const LANGUAGES = [
  { value: 'עברית', weight: 100 },
  { value: 'אנגלית', weight: 55 },
  { value: 'רוסית', weight: 15 },
  { value: 'ערבית', weight: 12 },
  { value: 'צרפתית', weight: 6 },
  { value: 'אמהרית', weight: 4 },
  { value: 'ספרדית', weight: 4 },
]

export const BANKS = [
  ['בנק הפועלים', '612'],
  ['בנק לאומי', '904'],
  ['בנק דיסקונט', '083'],
  ['מזרחי טפחות', '457'],
  ['בנק יהב', '129'],
  ['הבנק הבינלאומי', '031'],
]

// אולמות ומרכזי-כנסים — הכתובת כפי שתופיע בהצעה, והקואורדינטה ל-`set_project_coordinates`.
export const VENUES = [
  { name: 'אקספו תל אביב, ביתן 2', lat: 32.1063, lng: 34.8102, size: 'big' },
  { name: 'אקספו תל אביב, ביתן 10', lat: 32.1041, lng: 34.8081, size: 'big' },
  { name: 'בנייני האומה, ירושלים', lat: 31.7862, lng: 35.2037, size: 'big' },
  { name: 'מרכז הקונגרסים, חיפה', lat: 32.7959, lng: 35.0143, size: 'big' },
  { name: 'מלון דן פנורמה, תל אביב', lat: 32.0575, lng: 34.7614, size: 'medium' },
  { name: 'מלון דיוויד אינטרקונטיננטל, תל אביב', lat: 32.0631, lng: 34.7645, size: 'medium' },
  { name: 'מלון קראון פלאזה, ירושלים', lat: 31.7838, lng: 35.2016, size: 'medium' },
  { name: 'אולמי לאגו, ראשון לציון', lat: 31.9877, lng: 34.7605, size: 'medium' },
  { name: 'מרכז הכנסים, הרצליה פיתוח', lat: 32.1624, lng: 34.8009, size: 'medium' },
  { name: 'היכל התרבות, נתניה', lat: 32.3286, lng: 34.8554, size: 'medium' },
  { name: 'מלון ליאונרדו סיטי טאואר, רמת גן', lat: 32.0833, lng: 34.8025, size: 'medium' },
  { name: 'בית ציוני אמריקה, תל אביב', lat: 32.0716, lng: 34.7821, size: 'small' },
  { name: 'גני התערוכה, חדרה', lat: 32.4364, lng: 34.9215, size: 'small' },
  { name: 'חוות האירועים, בית זית', lat: 31.7863, lng: 35.1568, size: 'small' },
  { name: 'מרכז הכנסים, פארק המדע רחובות', lat: 31.9076, lng: 34.8062, size: 'small' },
  { name: 'מלון רויאל ביץ׳, תל אביב', lat: 32.0787, lng: 34.7663, size: 'small' },
  { name: 'אודיטוריום סמולרש, אוניברסיטת תל אביב', lat: 32.1133, lng: 34.8044, size: 'small' },
  { name: 'מלון הילטון, תל אביב', lat: 32.0913, lng: 34.7714, size: 'medium' },
  { name: 'מלון דן כרמל, חיפה', lat: 32.7994, lng: 34.9814, size: 'small' },
  { name: 'מרכז אירועים כפר המכביה, רמת גן', lat: 32.0806, lng: 34.8278, size: 'medium' },
]

// שמות-אירועים לפי סוג-לקוח. `annual` = שם שחוזר מדי שנה אצל אותו לקוח (§ה׳2 #5).
export const EVENT_TEMPLATES = {
  private_company: [
    { name: 'כנס לקוחות שנתי', annual: true, size: 'big' },
    { name: 'כנס טכנולוגיה שנתי', annual: true, size: 'big' },
    { name: 'השקת מוצר', size: 'medium' },
    { name: 'ערב הוקרה לעובדים', size: 'medium' },
    { name: 'יום עיון ללקוחות', size: 'medium' },
    { name: 'מפגש משקיעים רבעוני', size: 'small' },
    { name: 'כנס מכירות', size: 'medium' },
    { name: 'הכשרת מנהלים', size: 'small' },
    { name: 'יריד תעסוקה', size: 'medium' },
    { name: 'סדנת לקוחות', size: 'small' },
    { name: 'ערב גאלה שנתי', annual: true, size: 'big' },
    { name: 'כנס שותפים', size: 'medium' },
  ],
  production_company: [
    { name: 'כנס לקוח — רישום והכוונה', size: 'big' },
    { name: 'השקה מסחרית', size: 'medium' },
    { name: 'ערב ספונסרים', size: 'small' },
    { name: 'פסטיבל קיץ', size: 'big', months: [6, 7, 8] },
    { name: 'תערוכה מקצועית', size: 'big' },
    { name: 'אירוע חברה שנתי', annual: true, size: 'medium' },
    { name: 'טקס פרסים', size: 'medium' },
  ],
  government: [
    { name: 'טקס פרסים עירוני', size: 'medium' },
    { name: 'פסטיבל קיץ עירוני', size: 'big', months: [7, 8] },
    { name: 'כנס תושבים', size: 'medium' },
    { name: 'ערב הוקרה למתנדבים', size: 'small' },
    { name: 'יריד קהילה', size: 'medium' },
    { name: 'כנס חינוך שנתי', annual: true, size: 'big' },
  ],
  nonprofit: [
    { name: 'ערב התרמה שנתי', annual: true, size: 'medium' },
    { name: 'כנס מתנדבים', size: 'small' },
    { name: 'יום עיון', size: 'small' },
    { name: 'טקס הוקרה לתורמים', size: 'small' },
  ],
}

export const CANCEL_REASONS = {
  customer: [
    'הלקוח הודיע על דחיית האירוע למועד לא ידוע',
    'הלקוח ביטל בגלל קיצוץ תקציבי',
    'הלקוח איחד את האירוע עם כנס אחר',
    'הלקוח הודיע שהמרצה הראשי ביטל והאירוע ירד',
  ],
  force_majeure: ['מצב ביטחוני — הנחיות פיקוד העורף', 'סופה ואזהרת מזג אוויר קיצוני'],
  other: ['האולם ביטל את ההזמנה ולא נמצא מקום חלופי בזמן'],
}

export const FEEDBACK_NOTES = {
  high: [
    'הצוות היה אדיב ומקצועי, הרישום זרם בלי תורים.',
    'הדיילות הגיעו מוקדם והכול היה מוכן לפני שהאורחים הגיעו.',
    'שירות מצוין, נשמח לעבוד שוב.',
    null,
    null,
  ],
  mid: ['היה בסדר, היו כמה עיכובים בכניסה בשעת השיא.', 'סביר. התגים הגיעו עם טעות בשם אחד.', null],
  low: [
    'שתי דיילות איחרו והכניסה התעכבה חצי שעה.',
    'התגים לא תאמו את רשימת המוזמנים ונוצר בלגן בכניסה.',
    'לא היה מי שינהל את הצוות בשטח.',
  ],
}
