-- why: מ11 פזה ב׳ — סבב-טקסט שלישי (L3), 23/09/2026. אחרי L2, הצילומים ושאילתה על כל שדה גלוי במטען
--      (so_what · תת-שורות/חלונות/השוואות של אריחים · כותרות והערות גרפים · meta.notes) מצאו ארבעה אחרונים:
--      שתי תוויות-השוואה עם "n=" סטטיסטי (במ17 הדפדפן אף מציג אותו הפוך: "97=n"), ושתי הערות-שוליים במ08
--      עם מונחים פנימיים ("רצפת-המהותיות", "רווח סופי קפוא"). הכרעת-ישי 2 ("תחליט אתה").
--      🔒 לא כאן בכוונה: משפט-ההרשאה במ21 — ההערה ב-SQL קושרת אותו ל-§7.100 (הכרעת-ישי 17/09); הוא שאלה לישי.
-- what: 3 פונקציות, 4 החלפות — מ14 · מ17 (תווית-השוואה של ריכוזיות) · מ08 (שתי הערות-שוליים).
-- how: אותה טכניקה כמו L1/L2 — pg_get_functiondef + replace מדויק, "בדיוק פעם אחת" (אחרת raise), execute.
--      אותה חתימה ⇒ הרשאות והערות נשמרות. אין שינוי-סכמה ואין שינוי בנתונים.
-- verified before apply (23/09/2026): הגוף שממנו נבנו ההחלפות = הגוף החי אחרי L2 (md5 16/16).
-- reversible: כן — ההחלפות ההפוכות מחזירות; המצב הקודם שמור ב-L2 (+L1, j1/j2/j3, K1).
-- generated by: docs/specs/module_11_reports/phase-b-migration/gen-migration.mjs --ops ops-l3.mjs (לא נערך ידנית).
-- ═══ report_m14_hostess_overview — 1 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m14_hostess_overview';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'label', 'אשתקד (n=' || v_gini_prev_n || ')',$o0$, ''))) <> length($o0$'label', 'אשתקד (n=' || v_gini_prev_n || ')',$o0$) then
    raise exception 'm11 text report_m14_hostess_overview #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'label', 'אשתקד (n=' || v_gini_prev_n || ')',$o0$, $n0$'label', 'אשתקד',$n0$);
  execute v_def;
end $m11$;

-- ═══ report_m17_fairness — 1 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m17_fairness';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'label', 'אשתקד · ' || v_lri || 'n=' || coalesce(v_n_prev, 0) || v_pdi ||
                   ' מול ' || v_lri || 'n=' || coalesce(v_n, 0) || v_pdi || ' היום',$o0$, ''))) <> length($o0$'label', 'אשתקד · ' || v_lri || 'n=' || coalesce(v_n_prev, 0) || v_pdi ||
                   ' מול ' || v_lri || 'n=' || coalesce(v_n, 0) || v_pdi || ' היום',$o0$) then
    raise exception 'm11 text report_m17_fairness #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'label', 'אשתקד · ' || v_lri || 'n=' || coalesce(v_n_prev, 0) || v_pdi ||
                   ' מול ' || v_lri || 'n=' || coalesce(v_n, 0) || v_pdi || ' היום',$o0$, $n0$'label', 'אשתקד',$n0$);
  execute v_def;
end $m11$;

-- ═══ report_m08_profitability — 2 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m08_profitability';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$v_lri || v_floor_n || v_pdi || ' פרויקטים · '
          || v_lri || to_char(round(v_floor_sum), 'FM999,999,999') || ' ₪' || v_pdi
          || ' מתחת לרצפת-המהותיות (פחות מ-' || v_lri || '4' || v_pdi || ' שעות מתוכננות או פחות מ-'
          || v_lri || '1,000' || ' ₪' || v_pdi || ' עלות-עבודה מתוכננת) — הם בתוך האוכלוסייה '
          || 'ומחוץ לדירוג בלבד.',$o0$, ''))) <> length($o0$v_lri || v_floor_n || v_pdi || ' פרויקטים · '
          || v_lri || to_char(round(v_floor_sum), 'FM999,999,999') || ' ₪' || v_pdi
          || ' מתחת לרצפת-המהותיות (פחות מ-' || v_lri || '4' || v_pdi || ' שעות מתוכננות או פחות מ-'
          || v_lri || '1,000' || ' ₪' || v_pdi || ' עלות-עבודה מתוכננת) — הם בתוך האוכלוסייה '
          || 'ומחוץ לדירוג בלבד.',$o0$) then
    raise exception 'm11 text report_m08_profitability #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$v_lri || v_floor_n || v_pdi || ' פרויקטים · '
          || v_lri || to_char(round(v_floor_sum), 'FM999,999,999') || ' ₪' || v_pdi
          || ' מתחת לרצפת-המהותיות (פחות מ-' || v_lri || '4' || v_pdi || ' שעות מתוכננות או פחות מ-'
          || v_lri || '1,000' || ' ₪' || v_pdi || ' עלות-עבודה מתוכננת) — הם בתוך האוכלוסייה '
          || 'ומחוץ לדירוג בלבד.',$o0$, $n0$v_lri || v_floor_n || v_pdi || ' פרויקטים קטנים (פחות מ-' || v_lri || '4' || v_pdi || ' שעות או מ-'
          || v_lri || '1,000' || ' ₪' || v_pdi || ' עלות-עבודה) נספרים בסכומים, אבל לא בדירוג החריגות.',$n0$);
  if (length(v_def) - length(replace(v_def, $o1$'רווח: ' || v_lri || v_frozen || v_pdi || ' מתוך ' || v_lri || v_n || v_pdi
          || ' בתקופה נושאים רווח סופי קפוא; בשאר מוצג הרווח הגולמי המחושב.'),$o1$, ''))) <> length($o1$'רווח: ' || v_lri || v_frozen || v_pdi || ' מתוך ' || v_lri || v_n || v_pdi
          || ' בתקופה נושאים רווח סופי קפוא; בשאר מוצג הרווח הגולמי המחושב.'),$o1$) then
    raise exception 'm11 text report_m08_profitability #1: not exactly once'; end if;
  v_def := replace(v_def, $o1$'רווח: ' || v_lri || v_frozen || v_pdi || ' מתוך ' || v_lri || v_n || v_pdi
          || ' בתקופה נושאים רווח סופי קפוא; בשאר מוצג הרווח הגולמי המחושב.'),$o1$, $n1$'הרווח סופי ב-' || v_lri || v_frozen || v_pdi || ' מתוך ' || v_lri || v_n || v_pdi
          || ' הפרויקטים; בשאר הוא מחושב מהעלויות שנרשמו עד היום.'),$n1$);
  execute v_def;
end $m11$;
