-- why: מ11 פזה ב׳ — סבב-טקסט שני (L2), 23/09/2026. אחרי שמיגרציית-הטקסט L1 הוחלה, האימות החי של 12 הדוחות
--      (1536/1024 · מצב 0 ו-2) הראה שתת-השורות של האריחים — שלא היו בתחום של L1 — הן רוב הטקסט הגלוי שנשאר:
--      הגדרות על האריח, חזרה על שבב-ההיקף או על שורת-"אז מה", מילים פנימיות ("הדלי", "מדד משני",
--      "נספרות במכנה"), ושארית אחת ש-L1 עצמה השאירה ("לא אותה נוסחה" בלי נושא).
--      הכרעת-ישי 2 ("תחליט אתה") · ישי אישר את הסבב הזה בצ'אט 23/09 ("אתה יכול להמשיך בסבב הזה").
-- what: 8 פונקציות, 24 החלפות — תת-שורות אריחים בלבד (ועוד הערת-השוואה אחת במ07). הכלל: תת-שורה שהיא
--       הבסיס של המספר נשארת ("1,466 מתוך 1,682"); הגדרה, חזרה או הסבר-עיצוב — יורדים.
--       מ07 · מ14 · מ15 · מ16 · מ17 · מ19 · מ20 · מ22. מ3/מ4/מ6 לא נוגעים (יוחלפו).
-- how: אותה טכניקה כמו L1/K1 — pg_get_functiondef + replace מדויק, כל מחרוזת נבדקת "בדיוק פעם אחת"
--      (אחרת raise), ואז execute. אותה חתימה ⇒ הרשאות והערות נשמרות. אין שינוי-סכמה ואין שינוי בנתונים.
-- verified before apply (23/09/2026): הגוף שממנו נבנו ההחלפות = הגוף החי אחרי L1 (md5 13/13 —
--      docs/specs/module_11_reports/phase-b-migration/bodies.mjs + tools/grep-live.mjs).
-- reversible: כן — מצב-הגוף שלפני שמור ב-L1 (+j1/j2/j3/K1); החלה-חוזרת של ההחלפות ההפוכות מחזירה.
-- generated by: docs/specs/module_11_reports/phase-b-migration/gen-migration.mjs --ops ops-l2.mjs (לא נערך ידנית).
-- ═══ report_m07_finance_overview — 1 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m07_finance_overview';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'note', 'לא אותה נוסחה',$o0$, ''))) <> length($o0$'note', 'לא אותה נוסחה',$o0$) then
    raise exception 'm11 text report_m07_finance_overview #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'note', 'לא אותה נוסחה',$o0$, $n0$'note', null,$n0$);
  execute v_def;
end $m11$;

-- ═══ report_m14_hostess_overview — 3 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m14_hostess_overview';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'sub', 'מדד ג''יני · רבע הדיילות העמוסות ביותר מקבלות ' ||$o0$, ''))) <> length($o0$'sub', 'מדד ג''יני · רבע הדיילות העמוסות ביותר מקבלות ' ||$o0$) then
    raise exception 'm11 text report_m14_hostess_overview #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'sub', 'מדד ג''יני · רבע הדיילות העמוסות ביותר מקבלות ' ||$o0$, $n0$'sub', 'רבע הדיילות העמוסות ביותר מקבלות ' ||$n0$);
  if (length(v_def) - length(replace(v_def, $o1$'% מהמשמרות; מחצית המאגר מקבלת ' || coalesce(v_bottom_pct::text, '—') || '%'),$o1$, ''))) <> length($o1$'% מהמשמרות; מחצית המאגר מקבלת ' || coalesce(v_bottom_pct::text, '—') || '%'),$o1$) then
    raise exception 'm11 text report_m14_hostess_overview #1: not exactly once'; end if;
  v_def := replace(v_def, $o1$'% מהמשמרות; מחצית המאגר מקבלת ' || coalesce(v_bottom_pct::text, '—') || '%'),$o1$, $n1$'% מהמשמרות'),$n1$);
  if (length(v_def) - length(replace(v_def, $o2$' בענבר · ' || to_char(coalesce(v_red_active, 0), 'FM999,999,999') || ' מהאדומות פעילות'),$o2$, ''))) <> length($o2$' בענבר · ' || to_char(coalesce(v_red_active, 0), 'FM999,999,999') || ' מהאדומות פעילות'),$o2$) then
    raise exception 'm11 text report_m14_hostess_overview #2: not exactly once'; end if;
  v_def := replace(v_def, $o2$' בענבר · ' || to_char(coalesce(v_red_active, 0), 'FM999,999,999') || ' מהאדומות פעילות'),$o2$, $n2$' בענבר'),$n2$);
  execute v_def;
end $m11$;

-- ═══ report_m15_reliability — 1 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m15_reliability';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$ || ' · ' || to_char(coalesce(v_red_active, 0), 'FM999,999,999') || ' מהאדומות פעילות'))$o0$, ''))) <> length($o0$ || ' · ' || to_char(coalesce(v_red_active, 0), 'FM999,999,999') || ' מהאדומות פעילות'))$o0$) then
    raise exception 'm11 text report_m15_reliability #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$ || ' · ' || to_char(coalesce(v_red_active, 0), 'FM999,999,999') || ' מהאדומות פעילות'))$o0$, $n0$))$n0$);
  execute v_def;
end $m11$;

-- ═══ report_m16_quality_cost — 3 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m16_quality_cost';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'sub', 'מתוך ' || to_char(coalesce(v_active, 0), 'FM999,999,999') || ' הדיילות הפעילות'),$o0$, ''))) <> length($o0$'sub', 'מתוך ' || to_char(coalesce(v_active, 0), 'FM999,999,999') || ' הדיילות הפעילות'),$o0$) then
    raise exception 'm11 text report_m16_quality_cost #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'sub', 'מתוך ' || to_char(coalesce(v_active, 0), 'FM999,999,999') || ' הדיילות הפעילות'),$o0$, $n0$'sub', null),$n0$);
  if (length(v_def) - length(replace(v_def, $o1$'sub', 'על ' || to_char(coalesce(v_active, 0), 'FM999,999,999') || ' הדיילות הפעילות'),$o1$, ''))) <> length($o1$'sub', 'על ' || to_char(coalesce(v_active, 0), 'FM999,999,999') || ' הדיילות הפעילות'),$o1$) then
    raise exception 'm11 text report_m16_quality_cost #1: not exactly once'; end if;
  v_def := replace(v_def, $o1$'sub', 'על ' || to_char(coalesce(v_active, 0), 'FM999,999,999') || ' הדיילות הפעילות'),$o1$, $n1$'sub', null),$n1$);
  if (length(v_def) - length(replace(v_def, $o2$'sub', 'אצל לקוח אחד לפחות, מתוך ' || to_char(coalesce(v_active, 0), 'FM999,999,999') || ' הפעילות')),$o2$, ''))) <> length($o2$'sub', 'אצל לקוח אחד לפחות, מתוך ' || to_char(coalesce(v_active, 0), 'FM999,999,999') || ' הפעילות')),$o2$) then
    raise exception 'm11 text report_m16_quality_cost #2: not exactly once'; end if;
  v_def := replace(v_def, $o2$'sub', 'אצל לקוח אחד לפחות, מתוך ' || to_char(coalesce(v_active, 0), 'FM999,999,999') || ' הפעילות')),$o2$, $n2$'sub', 'אצל לקוח אחד לפחות')),$n2$);
  execute v_def;
end $m11$;

-- ═══ report_m17_fairness — 6 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m17_fairness';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'sub', 'מדד ג''יני · ' || v_lri || '0' || v_pdi || ' = חלוקה שווה בין הדיילות · ' ||
               v_lri || '1' || v_pdi || ' = דיילת אחת מקבלת הכול',$o0$, ''))) <> length($o0$'sub', 'מדד ג''יני · ' || v_lri || '0' || v_pdi || ' = חלוקה שווה בין הדיילות · ' ||
               v_lri || '1' || v_pdi || ' = דיילת אחת מקבלת הכול',$o0$) then
    raise exception 'm11 text report_m17_fairness #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'sub', 'מדד ג''יני · ' || v_lri || '0' || v_pdi || ' = חלוקה שווה בין הדיילות · ' ||
               v_lri || '1' || v_pdi || ' = דיילת אחת מקבלת הכול',$o0$, $n0$'sub', v_lri || '0' || v_pdi || ' = חלוקה שווה · ' ||
               v_lri || '1' || v_pdi || ' = הכול אצל דיילת אחת',$n0$);
  if (length(v_def) - length(replace(v_def, $o1$|| ' · מחצית המאגר מקבלת ' ||
               v_lri || coalesce(v_bottom_pct::text, '—') || '%' || v_pdi || ' · העשירון העליון ' ||
               v_lri || coalesce(v_top_dec_pct::text, '—') || '%' || v_pdi,$o1$, ''))) <> length($o1$|| ' · מחצית המאגר מקבלת ' ||
               v_lri || coalesce(v_bottom_pct::text, '—') || '%' || v_pdi || ' · העשירון העליון ' ||
               v_lri || coalesce(v_top_dec_pct::text, '—') || '%' || v_pdi,$o1$) then
    raise exception 'm11 text report_m17_fairness #1: not exactly once'; end if;
  v_def := replace(v_def, $o1$|| ' · מחצית המאגר מקבלת ' ||
               v_lri || coalesce(v_bottom_pct::text, '—') || '%' || v_pdi || ' · העשירון העליון ' ||
               v_lri || coalesce(v_top_dec_pct::text, '—') || '%' || v_pdi,$o1$, $n1$,$n1$);
  if (length(v_def) - length(replace(v_def, $o2$'sub', 'דרג ' || v_lri || '1' || v_pdi || ' = הדיילת שהמערכת דירגה ראשונה · ' ||$o2$, ''))) <> length($o2$'sub', 'דרג ' || v_lri || '1' || v_pdi || ' = הדיילת שהמערכת דירגה ראשונה · ' ||$o2$) then
    raise exception 'm11 text report_m17_fairness #2: not exactly once'; end if;
  v_def := replace(v_def, $o2$'sub', 'דרג ' || v_lri || '1' || v_pdi || ' = הדיילת שהמערכת דירגה ראשונה · ' ||$o2$, $n2$'sub',$n2$);
  if (length(v_def) - length(replace(v_def, $o3$then 'טרם נמדד — הרישום התחיל רק עכשיו'$o3$, ''))) <> length($o3$then 'טרם נמדד — הרישום התחיל רק עכשיו'$o3$) then
    raise exception 'm11 text report_m17_fairness #3: not exactly once'; end if;
  v_def := replace(v_def, $o3$then 'טרם נמדד — הרישום התחיל רק עכשיו'$o3$, $n3$then 'הרישום התחיל רק עכשיו'$n3$);
  if (length(v_def) - length(replace(v_def, $o4$'sub', 'שעות, מרגע שליחת הזימון האחרון ועד שהדיילת ענתה · ' ||$o4$, ''))) <> length($o4$'sub', 'שעות, מרגע שליחת הזימון האחרון ועד שהדיילת ענתה · ' ||$o4$) then
    raise exception 'm11 text report_m17_fairness #4: not exactly once'; end if;
  v_def := replace(v_def, $o4$'sub', 'שעות, מרגע שליחת הזימון האחרון ועד שהדיילת ענתה · ' ||$o4$, $n4$'sub', 'שעות · על ' ||$n4$);
  if (length(v_def) - length(replace(v_def, $o5$|| ' שזומנו · ' ||
               v_lri || to_char(coalesce(v_invites, 0) - coalesce(v_answered, 0), 'FM999,999') || v_pdi ||
               ' לא ענו כלל — והן נספרות במכנה',$o5$, ''))) <> length($o5$|| ' שזומנו · ' ||
               v_lri || to_char(coalesce(v_invites, 0) - coalesce(v_answered, 0), 'FM999,999') || v_pdi ||
               ' לא ענו כלל — והן נספרות במכנה',$o5$) then
    raise exception 'm11 text report_m17_fairness #5: not exactly once'; end if;
  v_def := replace(v_def, $o5$|| ' שזומנו · ' ||
               v_lri || to_char(coalesce(v_invites, 0) - coalesce(v_answered, 0), 'FM999,999') || v_pdi ||
               ' לא ענו כלל — והן נספרות במכנה',$o5$, $n5$|| ' שזומנו',$n5$);
  execute v_def;
end $m11$;

-- ═══ report_m19_customers_overview — 4 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m19_customers_overview';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'sub', 'משובים שליליים שתויגו "אחר" מתוך ' ||$o0$, ''))) <> length($o0$'sub', 'משובים שליליים שתויגו "אחר" מתוך ' ||$o0$) then
    raise exception 'm11 text report_m19_customers_overview #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'sub', 'משובים שליליים שתויגו "אחר" מתוך ' ||$o0$, $n0$'sub', 'תויגו "אחר" מתוך ' ||$n0$);
  if (length(v_def) - length(replace(v_def, $o1$|| ' — הדלי הגדול מכל ארבע הקטגוריות',$o1$, ''))) <> length($o1$|| ' — הדלי הגדול מכל ארבע הקטגוריות',$o1$) then
    raise exception 'm11 text report_m19_customers_overview #1: not exactly once'; end if;
  v_def := replace(v_def, $o1$|| ' — הדלי הגדול מכל ארבע הקטגוריות',$o1$, $n1$|| ' משובים שליליים',$n1$);
  if (length(v_def) - length(replace(v_def, $o2$|| ' מחמשת הלקוחות הגדולים — יחד '$o2$, ''))) <> length($o2$|| ' מחמשת הלקוחות הגדולים — יחד '$o2$) then
    raise exception 'm11 text report_m19_customers_overview #2: not exactly once'; end if;
  v_def := replace(v_def, $o2$|| ' מחמשת הלקוחות הגדולים — יחד '$o2$, $n2$|| ' מחמשת הגדולים ('$n2$);
  if (length(v_def) - length(replace(v_def, $o3$|| '%' || v_pdi || ' מהכנסת ' || v_lri || '12' || v_pdi
               || ' החודשים — מסומנים "מתרחק"',$o3$, ''))) <> length($o3$|| '%' || v_pdi || ' מהכנסת ' || v_lri || '12' || v_pdi
               || ' החודשים — מסומנים "מתרחק"',$o3$) then
    raise exception 'm11 text report_m19_customers_overview #3: not exactly once'; end if;
  v_def := replace(v_def, $o3$|| '%' || v_pdi || ' מהכנסת ' || v_lri || '12' || v_pdi
               || ' החודשים — מסומנים "מתרחק"',$o3$, $n3$|| '%' || v_pdi || ' מההכנסה) מסומנים "מתרחק"',$n3$);
  execute v_def;
end $m11$;

-- ═══ report_m20_satisfaction — 2 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m20_satisfaction';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$' משובים · מדד משני לשיעור-המרוצים',$o0$, ''))) <> length($o0$' משובים · מדד משני לשיעור-המרוצים',$o0$) then
    raise exception 'm11 text report_m20_satisfaction #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$' משובים · מדד משני לשיעור-המרוצים',$o0$, $n0$' משובים',$n0$);
  if (length(v_def) - length(replace(v_def, $o1$' — ו-'
               || v_lri || to_char(v_with_pos, 'FM999,999,999') || v_pdi || ' סימנו סיבה חיובית',$o1$, ''))) <> length($o1$' — ו-'
               || v_lri || to_char(v_with_pos, 'FM999,999,999') || v_pdi || ' סימנו סיבה חיובית',$o1$) then
    raise exception 'm11 text report_m20_satisfaction #1: not exactly once'; end if;
  v_def := replace(v_def, $o1$' — ו-'
               || v_lri || to_char(v_with_pos, 'FM999,999,999') || v_pdi || ' סימנו סיבה חיובית',$o1$, $n1$' משובים',$n1$);
  execute v_def;
end $m11$;

-- ═══ report_m22_notes — 4 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m22_notes';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'sub', 'מתוך ' || v_lri || to_char(v_completed, 'FM999,999,999') || v_pdi || ' משובים שהושלמו ('
               || v_lri || coalesce(to_char(round(100.0 * v_with_note / nullif(v_completed, 0), 1), 'FM999990.0'), '—')
               || '%' || v_pdi || ' כתבו משהו) · ' || v_lri || to_char(v_distinct, 'FM999,999,999') || v_pdi || ' נוסחים שונים',$o0$, ''))) <> length($o0$'sub', 'מתוך ' || v_lri || to_char(v_completed, 'FM999,999,999') || v_pdi || ' משובים שהושלמו ('
               || v_lri || coalesce(to_char(round(100.0 * v_with_note / nullif(v_completed, 0), 1), 'FM999990.0'), '—')
               || '%' || v_pdi || ' כתבו משהו) · ' || v_lri || to_char(v_distinct, 'FM999,999,999') || v_pdi || ' נוסחים שונים',$o0$) then
    raise exception 'm11 text report_m22_notes #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'sub', 'מתוך ' || v_lri || to_char(v_completed, 'FM999,999,999') || v_pdi || ' משובים שהושלמו ('
               || v_lri || coalesce(to_char(round(100.0 * v_with_note / nullif(v_completed, 0), 1), 'FM999990.0'), '—')
               || '%' || v_pdi || ' כתבו משהו) · ' || v_lri || to_char(v_distinct, 'FM999,999,999') || v_pdi || ' נוסחים שונים',$o0$, $n0$'sub', null,$n0$);
  if (length(v_def) - length(replace(v_def, $o1$then 'לכל ' || v_lri || to_char(v_other, 'FM999,999,999') || v_pdi || ' יש טקסט — אין ולו אחת ריקה'$o1$, ''))) <> length($o1$then 'לכל ' || v_lri || to_char(v_other, 'FM999,999,999') || v_pdi || ' יש טקסט — אין ולו אחת ריקה'$o1$) then
    raise exception 'm11 text report_m22_notes #1: not exactly once'; end if;
  v_def := replace(v_def, $o1$then 'לכל ' || v_lri || to_char(v_other, 'FM999,999,999') || v_pdi || ' יש טקסט — אין ולו אחת ריקה'$o1$, $n1$then 'כולן עם טקסט'$n1$);
  if (length(v_def) - length(replace(v_def, $o2$then 'טרם אושרה ריצה — לא 0. אפס כאן היה נקרא "אין בעיות", וזו אמירה שאיש לא בדק'$o2$, ''))) <> length($o2$then 'טרם אושרה ריצה — לא 0. אפס כאן היה נקרא "אין בעיות", וזו אמירה שאיש לא בדק'$o2$) then
    raise exception 'm11 text report_m22_notes #2: not exactly once'; end if;
  v_def := replace(v_def, $o2$then 'טרם אושרה ריצה — לא 0. אפס כאן היה נקרא "אין בעיות", וזו אמירה שאיש לא בדק'$o2$, $n2$then 'טרם אושרה ריצה'$n2$);
  if (length(v_def) - length(replace(v_def, $o3$|| case when v_run_cnt > 1
                                 then ' · ' || v_lri || to_char(v_run_cnt, 'FM999,999,999') || v_pdi || ' ריצות מאושרות'
                                 else '' end end,$o3$, ''))) <> length($o3$|| case when v_run_cnt > 1
                                 then ' · ' || v_lri || to_char(v_run_cnt, 'FM999,999,999') || v_pdi || ' ריצות מאושרות'
                                 else '' end end,$o3$) then
    raise exception 'm11 text report_m22_notes #3: not exactly once'; end if;
  v_def := replace(v_def, $o3$|| case when v_run_cnt > 1
                                 then ' · ' || v_lri || to_char(v_run_cnt, 'FM999,999,999') || v_pdi || ' ריצות מאושרות'
                                 else '' end end,$o3$, $n3$end,$n3$);
  execute v_def;
end $m11$;
