-- why: מ11 פזה ב׳ (טיפוגרפיה וניסוח) — מיגרציית-הטקסט. הכרעת-ישי 23/09/2026: הניסוחים של הדוחות חיים
--      בגוף פונקציות ה-SQL, ולכן נכתבים מחדש כאן ולא בדריסה בצד-הלקוח (מקור-אמת אחד).
--      התוכנית: docs/plans/2026-09-17-module-11-typography.md §7 פזה ב׳ · הבלוק "🗣️ אושר 23/09/2026".
-- what: 13 פונקציות-דוח (מ3/מ4/מ6 לא נוגעים — יוחלפו). לכל אחת: population.summary חדש (שבב-ההיקף) ·
--       שורת-"אז מה" מקוצרת · תת-שורות והערות-השוואה שחוזרות על המסך יורדות · כל "אינו מושפע ממסנן…" יורד ·
--       קודים פנימיים (📐13) יורדים מהמסך. ובנוסף: מ20 — שני גרפים נמחקים ("מה מכעיס", "שיעור המרוצים
--       לפי שנה"); מ22 — אריח other_vs_categories נמחק (אותו v_other פעמיים); מ09 — drill_key לדאטום
--       של הגרף (הדלת של השורה); מ15 — period_filter_ignored + תווית-חלון עובדתית.
-- how: אותה טכניקה כמו K1 — pg_get_functiondef + replace מדויק, **כל מחרוזת נבדקת שהיא מופיעה בדיוק
--      פעם אחת לפני ההחלפה** (אחרת raise), ואז execute. אותה חתימה ⇒ CREATE OR REPLACE שומר הרשאות
--      והערות; אין drop, אין overload, אין שינוי-סכמה, אין שינוי בנתונים.
-- verified before apply (23/09/2026): md5(prosrc) החי של כל 13 הפונקציות == גוף-הקובץ האחרון
--      (אחרי טלאי K1 במ02/מ07/מ19) ⇒ כל 86 המחרוזות קיימות בדיוק כפי שהן כאן.
-- reversible: כן — הגופים הקודמים שמורים במיגרציות j1/j2/j3 (+K1); החלה-חוזרת שלהם מחזירה את הטקסט.
-- generated by: docs/specs/module_11_reports/phase-b-migration/gen-migration.mjs מתוך ops.mjs שם (לא נערך ידנית).

-- ═══ report_m02_exec_overview — 15 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m02_exec_overview';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$v_so_what := 'לשים לב שאין טווח מקביל אשתקד למדוד מולו — ' ||
      v_lri || to_char(round(v_rev), 'FM999,999,999') || ' ₪' || v_pdi || ' מתחילת התקופה, שולי-רווח ' ||
      v_lri || to_char(round(v_margin, 1), 'FM990.0') || '%' || v_pdi || '.';$o0$, ''))) <> length($o0$v_so_what := 'לשים לב שאין טווח מקביל אשתקד למדוד מולו — ' ||
      v_lri || to_char(round(v_rev), 'FM999,999,999') || ' ₪' || v_pdi || ' מתחילת התקופה, שולי-רווח ' ||
      v_lri || to_char(round(v_margin, 1), 'FM990.0') || '%' || v_pdi || '.';$o0$) then
    raise exception 'm11 text report_m02_exec_overview #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$v_so_what := 'לשים לב שאין טווח מקביל אשתקד למדוד מולו — ' ||
      v_lri || to_char(round(v_rev), 'FM999,999,999') || ' ₪' || v_pdi || ' מתחילת התקופה, שולי-רווח ' ||
      v_lri || to_char(round(v_margin, 1), 'FM990.0') || '%' || v_pdi || '.';$o0$, $n0$v_so_what := 'לשים לב שאין טווח מקביל אשתקד להשוואה; שולי-הרווח עומדים על ' ||
      v_lri || to_char(round(v_margin, 1), 'FM990.0') || '%' || v_pdi || '.';$n0$);
  if (length(v_def) - length(replace(v_def, $o1$v_so_what := 'לשים לב שהצמיחה השנה לא באה על חשבון הרווח — ' ||
      v_lri || to_char(round(v_rev), 'FM999,999,999') || ' ₪' || v_pdi || ' עד ' ||
      v_lri || to_char(v_to, 'DD/MM') || v_pdi || ', גידול של ' ||
      v_lri || to_char(round(v_growth, 1), 'FM990.0') || '%' || v_pdi ||
      ' מול אותו טווח אשתקד, ושולי-הרווח דווקא עלו ל-' ||
      v_lri || to_char(round(v_margin, 1), 'FM990.0') || '%' || v_pdi || '. הפירוט בדוח «מגמות רב-שנתיות».';$o1$, ''))) <> length($o1$v_so_what := 'לשים לב שהצמיחה השנה לא באה על חשבון הרווח — ' ||
      v_lri || to_char(round(v_rev), 'FM999,999,999') || ' ₪' || v_pdi || ' עד ' ||
      v_lri || to_char(v_to, 'DD/MM') || v_pdi || ', גידול של ' ||
      v_lri || to_char(round(v_growth, 1), 'FM990.0') || '%' || v_pdi ||
      ' מול אותו טווח אשתקד, ושולי-הרווח דווקא עלו ל-' ||
      v_lri || to_char(round(v_margin, 1), 'FM990.0') || '%' || v_pdi || '. הפירוט בדוח «מגמות רב-שנתיות».';$o1$) then
    raise exception 'm11 text report_m02_exec_overview #1: not exactly once'; end if;
  v_def := replace(v_def, $o1$v_so_what := 'לשים לב שהצמיחה השנה לא באה על חשבון הרווח — ' ||
      v_lri || to_char(round(v_rev), 'FM999,999,999') || ' ₪' || v_pdi || ' עד ' ||
      v_lri || to_char(v_to, 'DD/MM') || v_pdi || ', גידול של ' ||
      v_lri || to_char(round(v_growth, 1), 'FM990.0') || '%' || v_pdi ||
      ' מול אותו טווח אשתקד, ושולי-הרווח דווקא עלו ל-' ||
      v_lri || to_char(round(v_margin, 1), 'FM990.0') || '%' || v_pdi || '. הפירוט בדוח «מגמות רב-שנתיות».';$o1$, $n1$v_so_what := 'לשים לב שההכנסות גבוהות ב-' ||
      v_lri || to_char(round(v_growth, 1), 'FM990.0') || '%' || v_pdi || ' מאשתקד, ושולי-הרווח עלו ל-' ||
      v_lri || to_char(round(v_margin, 1), 'FM990.0') || '%' || v_pdi || '.';$n1$);
  if (length(v_def) - length(replace(v_def, $o2$v_so_what := 'לשים לב שהצמיחה השנה באה על חשבון הרווח — ' ||
      v_lri || to_char(round(v_rev), 'FM999,999,999') || ' ₪' || v_pdi || ' עד ' ||
      v_lri || to_char(v_to, 'DD/MM') || v_pdi || ', גידול של ' ||
      v_lri || to_char(round(v_growth, 1), 'FM990.0') || '%' || v_pdi ||
      ' מול אותו טווח אשתקד, אך שולי-הרווח ירדו ל-' ||
      v_lri || to_char(round(v_margin, 1), 'FM990.0') || '%' || v_pdi ||
      ' מול ' || v_lri || to_char(round(v_prev_margin, 1), 'FM990.0') || '%' || v_pdi ||
      '. הפירוט בדוח «מגמות רב-שנתיות».';$o2$, ''))) <> length($o2$v_so_what := 'לשים לב שהצמיחה השנה באה על חשבון הרווח — ' ||
      v_lri || to_char(round(v_rev), 'FM999,999,999') || ' ₪' || v_pdi || ' עד ' ||
      v_lri || to_char(v_to, 'DD/MM') || v_pdi || ', גידול של ' ||
      v_lri || to_char(round(v_growth, 1), 'FM990.0') || '%' || v_pdi ||
      ' מול אותו טווח אשתקד, אך שולי-הרווח ירדו ל-' ||
      v_lri || to_char(round(v_margin, 1), 'FM990.0') || '%' || v_pdi ||
      ' מול ' || v_lri || to_char(round(v_prev_margin, 1), 'FM990.0') || '%' || v_pdi ||
      '. הפירוט בדוח «מגמות רב-שנתיות».';$o2$) then
    raise exception 'm11 text report_m02_exec_overview #2: not exactly once'; end if;
  v_def := replace(v_def, $o2$v_so_what := 'לשים לב שהצמיחה השנה באה על חשבון הרווח — ' ||
      v_lri || to_char(round(v_rev), 'FM999,999,999') || ' ₪' || v_pdi || ' עד ' ||
      v_lri || to_char(v_to, 'DD/MM') || v_pdi || ', גידול של ' ||
      v_lri || to_char(round(v_growth, 1), 'FM990.0') || '%' || v_pdi ||
      ' מול אותו טווח אשתקד, אך שולי-הרווח ירדו ל-' ||
      v_lri || to_char(round(v_margin, 1), 'FM990.0') || '%' || v_pdi ||
      ' מול ' || v_lri || to_char(round(v_prev_margin, 1), 'FM990.0') || '%' || v_pdi ||
      '. הפירוט בדוח «מגמות רב-שנתיות».';$o2$, $n2$v_so_what := 'לשים לב שההכנסות גבוהות ב-' ||
      v_lri || to_char(round(v_growth, 1), 'FM990.0') || '%' || v_pdi || ' מאשתקד, אך שולי-הרווח ירדו ל-' ||
      v_lri || to_char(round(v_margin, 1), 'FM990.0') || '%' || v_pdi || ' מ-' ||
      v_lri || to_char(round(v_prev_margin, 1), 'FM990.0') || '%' || v_pdi || '.';$n2$);
  if (length(v_def) - length(replace(v_def, $o3$v_so_what := 'לשים לב שההכנסות נמוכות מאותו טווח אשתקד — ' ||
      v_lri || to_char(round(v_rev), 'FM999,999,999') || ' ₪' || v_pdi || ' מול ' ||
      v_lri || to_char(round(v_prev_rev), 'FM999,999,999') || ' ₪' || v_pdi ||
      ', ושולי-הרווח על ' || v_lri || to_char(round(v_margin, 1), 'FM990.0') || '%' || v_pdi ||
      '. הפירוט בדוח «מגמות רב-שנתיות».';$o3$, ''))) <> length($o3$v_so_what := 'לשים לב שההכנסות נמוכות מאותו טווח אשתקד — ' ||
      v_lri || to_char(round(v_rev), 'FM999,999,999') || ' ₪' || v_pdi || ' מול ' ||
      v_lri || to_char(round(v_prev_rev), 'FM999,999,999') || ' ₪' || v_pdi ||
      ', ושולי-הרווח על ' || v_lri || to_char(round(v_margin, 1), 'FM990.0') || '%' || v_pdi ||
      '. הפירוט בדוח «מגמות רב-שנתיות».';$o3$) then
    raise exception 'm11 text report_m02_exec_overview #3: not exactly once'; end if;
  v_def := replace(v_def, $o3$v_so_what := 'לשים לב שההכנסות נמוכות מאותו טווח אשתקד — ' ||
      v_lri || to_char(round(v_rev), 'FM999,999,999') || ' ₪' || v_pdi || ' מול ' ||
      v_lri || to_char(round(v_prev_rev), 'FM999,999,999') || ' ₪' || v_pdi ||
      ', ושולי-הרווח על ' || v_lri || to_char(round(v_margin, 1), 'FM990.0') || '%' || v_pdi ||
      '. הפירוט בדוח «מגמות רב-שנתיות».';$o3$, $n3$v_so_what := 'לשים לב שההכנסות נמוכות ב-' ||
      v_lri || to_char(round(-v_growth, 1), 'FM990.0') || '%' || v_pdi || ' מאשתקד; שולי-הרווח עומדים על ' ||
      v_lri || to_char(round(v_margin, 1), 'FM990.0') || '%' || v_pdi || '.';$n3$);
  if (length(v_def) - length(replace(v_def, $o4$'label', 'אוכלוסייה: אירועים שכבר התקיימו וסגורים תפעולית — פרויקט הסתיים · ממתין לסגירה · ממתין לחשבונית · ממתין לתשלום · הוצאו: אירועים שטרם התקיימו, אירועים בתהליך ואירועים מבוטלים · ' ||
        v_lri || 'n=' || to_char(v_n, 'FM999,999,999') || v_pdi || ' (מתוך ' || v_lri || to_char(v_projects_all, 'FM999,999,999') || v_pdi ||
        case when p_customer_id is null then ' אירועים במערכת).' else ' אירועים של הלקוח).' end,$o4$, ''))) <> length($o4$'label', 'אוכלוסייה: אירועים שכבר התקיימו וסגורים תפעולית — פרויקט הסתיים · ממתין לסגירה · ממתין לחשבונית · ממתין לתשלום · הוצאו: אירועים שטרם התקיימו, אירועים בתהליך ואירועים מבוטלים · ' ||
        v_lri || 'n=' || to_char(v_n, 'FM999,999,999') || v_pdi || ' (מתוך ' || v_lri || to_char(v_projects_all, 'FM999,999,999') || v_pdi ||
        case when p_customer_id is null then ' אירועים במערכת).' else ' אירועים של הלקוח).' end,$o4$) then
    raise exception 'm11 text report_m02_exec_overview #4: not exactly once'; end if;
  v_def := replace(v_def, $o4$'label', 'אוכלוסייה: אירועים שכבר התקיימו וסגורים תפעולית — פרויקט הסתיים · ממתין לסגירה · ממתין לחשבונית · ממתין לתשלום · הוצאו: אירועים שטרם התקיימו, אירועים בתהליך ואירועים מבוטלים · ' ||
        v_lri || 'n=' || to_char(v_n, 'FM999,999,999') || v_pdi || ' (מתוך ' || v_lri || to_char(v_projects_all, 'FM999,999,999') || v_pdi ||
        case when p_customer_id is null then ' אירועים במערכת).' else ' אירועים של הלקוח).' end,$o4$, $n4$'summary', v_lri || to_char(v_n, 'FM999,999,999') || v_pdi || ' אירועים שהסתיימו · מתוך ' ||
        v_lri || to_char(v_projects_all, 'FM999,999,999') || v_pdi,
      'label', 'נכללים אירועים שכבר התקיימו: הסתיים, ממתין לסגירה, ממתין לחשבונית או ממתין לתשלום. לא נכללים אירועים עתידיים, בתהליך או מבוטלים.',$n4$);
  if (length(v_def) - length(replace(v_def, $o5$'sub', v_lri || to_char(v_n, 'FM999,999,999') || v_pdi || ' אירועים שהסתיימו',$o5$, ''))) <> length($o5$'sub', v_lri || to_char(v_n, 'FM999,999,999') || v_pdi || ' אירועים שהסתיימו',$o5$) then
    raise exception 'm11 text report_m02_exec_overview #5: not exactly once'; end if;
  v_def := replace(v_def, $o5$'sub', v_lri || to_char(v_n, 'FM999,999,999') || v_pdi || ' אירועים שהסתיימו',$o5$, $n5$'sub', null,$n5$);
  if (length(v_def) - length(replace(v_def, $o6$'note', v_lri || to_char(v_prev_n, 'FM999,999,999') || v_pdi || ' אירועים',$o6$, ''))) <> length($o6$'note', v_lri || to_char(v_prev_n, 'FM999,999,999') || v_pdi || ' אירועים',$o6$) then
    raise exception 'm11 text report_m02_exec_overview #6: not exactly once'; end if;
  v_def := replace(v_def, $o6$'note', v_lri || to_char(v_prev_n, 'FM999,999,999') || v_pdi || ' אירועים',$o6$, $n6$'note', null,$n6$);
  if (length(v_def) - length(replace(v_def, $o7$'sub', v_lri || to_char(round(v_prof), 'FM999,999,999') || ' ₪' || v_pdi || ' רווח מתוך ' ||
               v_lri || to_char(round(v_rev), 'FM999,999,999') || ' ₪' || v_pdi || ' הכנסה',$o7$, ''))) <> length($o7$'sub', v_lri || to_char(round(v_prof), 'FM999,999,999') || ' ₪' || v_pdi || ' רווח מתוך ' ||
               v_lri || to_char(round(v_rev), 'FM999,999,999') || ' ₪' || v_pdi || ' הכנסה',$o7$) then
    raise exception 'm11 text report_m02_exec_overview #7: not exactly once'; end if;
  v_def := replace(v_def, $o7$'sub', v_lri || to_char(round(v_prof), 'FM999,999,999') || ' ₪' || v_pdi || ' רווח מתוך ' ||
               v_lri || to_char(round(v_rev), 'FM999,999,999') || ' ₪' || v_pdi || ' הכנסה',$o7$, $n7$'sub', null,$n7$);
  if (length(v_def) - length(replace(v_def, $o8$'sub', 'ארבעת המצבים — פרויקט הסתיים · ממתין לסגירה · ממתין לחשבונית · ממתין לתשלום',$o8$, ''))) <> length($o8$'sub', 'ארבעת המצבים — פרויקט הסתיים · ממתין לסגירה · ממתין לחשבונית · ממתין לתשלום',$o8$) then
    raise exception 'm11 text report_m02_exec_overview #8: not exactly once'; end if;
  v_def := replace(v_def, $o8$'sub', 'ארבעת המצבים — פרויקט הסתיים · ממתין לסגירה · ממתין לחשבונית · ממתין לתשלום',$o8$, $n8$'sub', null,$n8$);
  if (length(v_def) - length(replace(v_def, $o9$'sub', v_lri || to_char(round(v_top5), 'FM999,999,999') || ' ₪' || v_pdi || ' מתוך ' ||
               v_lri || to_char(round(v_total_rev), 'FM999,999,999') || ' ₪' || v_pdi || ' · אצל ' ||
               v_lri || to_char(v_ncust, 'FM999,999,999') || v_pdi || ' לקוחות עם הכנסה (מתוך ' || v_lri || to_char(v_customers_all, 'FM999,999,999') || v_pdi || ' רשומים)',$o9$, ''))) <> length($o9$'sub', v_lri || to_char(round(v_top5), 'FM999,999,999') || ' ₪' || v_pdi || ' מתוך ' ||
               v_lri || to_char(round(v_total_rev), 'FM999,999,999') || ' ₪' || v_pdi || ' · אצל ' ||
               v_lri || to_char(v_ncust, 'FM999,999,999') || v_pdi || ' לקוחות עם הכנסה (מתוך ' || v_lri || to_char(v_customers_all, 'FM999,999,999') || v_pdi || ' רשומים)',$o9$) then
    raise exception 'm11 text report_m02_exec_overview #9: not exactly once'; end if;
  v_def := replace(v_def, $o9$'sub', v_lri || to_char(round(v_top5), 'FM999,999,999') || ' ₪' || v_pdi || ' מתוך ' ||
               v_lri || to_char(round(v_total_rev), 'FM999,999,999') || ' ₪' || v_pdi || ' · אצל ' ||
               v_lri || to_char(v_ncust, 'FM999,999,999') || v_pdi || ' לקוחות עם הכנסה (מתוך ' || v_lri || to_char(v_customers_all, 'FM999,999,999') || v_pdi || ' רשומים)',$o9$, $n9$'sub', null,$n9$);
  if (length(v_def) - length(replace(v_def, $o10$'window', 'כל הזמנים · אינו מושפע ממסנן התקופה',$o10$, ''))) <> length($o10$'window', 'כל הזמנים · אינו מושפע ממסנן התקופה',$o10$) then
    raise exception 'm11 text report_m02_exec_overview #10: not exactly once'; end if;
  v_def := replace(v_def, $o10$'window', 'כל הזמנים · אינו מושפע ממסנן התקופה',$o10$, $n10$'window', case when p_customer_id is null then 'כל הזמנים' else 'כל הזמנים · כל הלקוחות' end,$n10$);
  if (length(v_def) - length(replace(v_def, $o11$'note', 'אז ' || v_lri || to_char(v_prev_ncust, 'FM999,999,999') || v_pdi || ' לקוחות עם הכנסה',$o11$, ''))) <> length($o11$'note', 'אז ' || v_lri || to_char(v_prev_ncust, 'FM999,999,999') || v_pdi || ' לקוחות עם הכנסה',$o11$) then
    raise exception 'm11 text report_m02_exec_overview #11: not exactly once'; end if;
  v_def := replace(v_def, $o11$'note', 'אז ' || v_lri || to_char(v_prev_ncust, 'FM999,999,999') || v_pdi || ' לקוחות עם הכנסה',$o11$, $n11$'note', null,$n11$);
  if (length(v_def) - length(replace(v_def, $o12$if p_customer_id is not null then
    v_notes := v_notes || to_jsonb(
      'אריח «נתח 5 הלקוחות הגדולים» נמדד על כל הלקוחות ואינו מושפע ממסנן-הלקוח — נתח של לקוח יחיד מול עצמו הוא תמיד 100%.'::text);
  end if;$o12$, ''))) <> length($o12$if p_customer_id is not null then
    v_notes := v_notes || to_jsonb(
      'אריח «נתח 5 הלקוחות הגדולים» נמדד על כל הלקוחות ואינו מושפע ממסנן-הלקוח — נתח של לקוח יחיד מול עצמו הוא תמיד 100%.'::text);
  end if;$o12$) then
    raise exception 'm11 text report_m02_exec_overview #12: not exactly once'; end if;
  v_def := replace(v_def, $o12$if p_customer_id is not null then
    v_notes := v_notes || to_jsonb(
      'אריח «נתח 5 הלקוחות הגדולים» נמדד על כל הלקוחות ואינו מושפע ממסנן-הלקוח — נתח של לקוח יחיד מול עצמו הוא תמיד 100%.'::text);
  end if;$o12$, $n12$-- ✏️ פזה ב׳ 23/09/2026: הסייג עבר לחלון-האריח ("כל הזמנים · כל הלקוחות").$n12$);
  if (length(v_def) - length(replace(v_def, $o13$'מבט-על הנהלה אינו דוח-קידוח (📐13) — פרמטר הקידוח מתעלמים ממנו.'$o13$, ''))) <> length($o13$'מבט-על הנהלה אינו דוח-קידוח (📐13) — פרמטר הקידוח מתעלמים ממנו.'$o13$) then
    raise exception 'm11 text report_m02_exec_overview #13: not exactly once'; end if;
  v_def := replace(v_def, $o13$'מבט-על הנהלה אינו דוח-קידוח (📐13) — פרמטר הקידוח מתעלמים ממנו.'$o13$, $n13$'הדוח הזה אינו תומך בקידוח.'$n13$);
  if (length(v_def) - length(replace(v_def, $o14$'definitions', 'שולי-רווח = סך הרווח הגולמי חלקי סך ההכנסה על כל האוכלוסייה יחד, לא ממוצע של אחוזים · רווח גולמי = הכנסה פחות עלויות ישירות (דיילות · ציוד · נסיעות); הוצאות המשרד אינן נכללות · נתח 5 הלקוחות הגדולים = הכנסת חמשת הגדולים חלקי הכנסת כל הלקוחות, על כל ההיסטוריה · "אשתקד" = אותם ימים בדיוק בשנה שעברה.',$o14$, ''))) <> length($o14$'definitions', 'שולי-רווח = סך הרווח הגולמי חלקי סך ההכנסה על כל האוכלוסייה יחד, לא ממוצע של אחוזים · רווח גולמי = הכנסה פחות עלויות ישירות (דיילות · ציוד · נסיעות); הוצאות המשרד אינן נכללות · נתח 5 הלקוחות הגדולים = הכנסת חמשת הגדולים חלקי הכנסת כל הלקוחות, על כל ההיסטוריה · "אשתקד" = אותם ימים בדיוק בשנה שעברה.',$o14$) then
    raise exception 'm11 text report_m02_exec_overview #14: not exactly once'; end if;
  v_def := replace(v_def, $o14$'definitions', 'שולי-רווח = סך הרווח הגולמי חלקי סך ההכנסה על כל האוכלוסייה יחד, לא ממוצע של אחוזים · רווח גולמי = הכנסה פחות עלויות ישירות (דיילות · ציוד · נסיעות); הוצאות המשרד אינן נכללות · נתח 5 הלקוחות הגדולים = הכנסת חמשת הגדולים חלקי הכנסת כל הלקוחות, על כל ההיסטוריה · "אשתקד" = אותם ימים בדיוק בשנה שעברה.',$o14$, $n14$'definitions', 'שולי-רווח = סך הרווח הגולמי חלקי סך ההכנסה, על כל האירועים יחד · רווח גולמי = הכנסה פחות עלויות ישירות (דיילות, ציוד, נסיעות), בלי הוצאות משרד · נתח 5 הלקוחות הגדולים = ' ||
      v_lri || to_char(round(v_top5), 'FM999,999,999') || ' ₪' || v_pdi || ' מתוך ' ||
      v_lri || to_char(round(v_total_rev), 'FM999,999,999') || ' ₪' || v_pdi || ', על כל ההיסטוריה · "אשתקד" = אותם ימים בדיוק בשנה שעברה.',$n14$);
  execute v_def;
end $m11$;

-- ═══ report_m07_finance_overview — 8 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m07_finance_overview';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'label', 'אוכלוסייה: חשבוניות שנשלחו וטרם שולמו · הוצאו: חובות אבודים ('$o0$, ''))) <> length($o0$'label', 'אוכלוסייה: חשבוניות שנשלחו וטרם שולמו · הוצאו: חובות אבודים ('$o0$) then
    raise exception 'm11 text report_m07_finance_overview #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'label', 'אוכלוסייה: חשבוניות שנשלחו וטרם שולמו · הוצאו: חובות אבודים ('$o0$, $n0$'summary', v_lri || v_open_n || v_pdi || case when v_open_n = 1 then ' חשבונית פתוחה' else ' חשבוניות פתוחות' end,
      'label', 'אוכלוסייה: חשבוניות שנשלחו וטרם שולמו · הוצאו: חובות אבודים ('$n0$);
  if (length(v_def) - length(replace(v_def, $o1$' חשבוניות, נכון להיום — צילום-רגע שאינו מושפע ממסנן התקופה. '$o1$, ''))) <> length($o1$' חשבוניות, נכון להיום — צילום-רגע שאינו מושפע ממסנן התקופה. '$o1$) then
    raise exception 'm11 text report_m07_finance_overview #1: not exactly once'; end if;
  v_def := replace(v_def, $o1$' חשבוניות, נכון להיום — צילום-רגע שאינו מושפע ממסנן התקופה. '$o1$, $n1$' חשבוניות, נכון להיום. '$n1$);
  if (length(v_def) - length(replace(v_def, $o2$|| ', אצל ' || coalesce(v_oldest_name, '—') || '; יתרת-החוב כולה עומדת על '
        || v_lri || to_char(round(v_open_sum), 'FM999,999,999') || ' ₪' || v_pdi || '.'
      else 'אין חוב מעל ' || v_lri || '60' || v_pdi || ' יום; יתרת-החוב הפתוחה עומדת על '
        || v_lri || to_char(round(v_open_sum), 'FM999,999,999') || ' ₪' || v_pdi || '.' end,$o2$, ''))) <> length($o2$|| ', אצל ' || coalesce(v_oldest_name, '—') || '; יתרת-החוב כולה עומדת על '
        || v_lri || to_char(round(v_open_sum), 'FM999,999,999') || ' ₪' || v_pdi || '.'
      else 'אין חוב מעל ' || v_lri || '60' || v_pdi || ' יום; יתרת-החוב הפתוחה עומדת על '
        || v_lri || to_char(round(v_open_sum), 'FM999,999,999') || ' ₪' || v_pdi || '.' end,$o2$) then
    raise exception 'm11 text report_m07_finance_overview #2: not exactly once'; end if;
  v_def := replace(v_def, $o2$|| ', אצל ' || coalesce(v_oldest_name, '—') || '; יתרת-החוב כולה עומדת על '
        || v_lri || to_char(round(v_open_sum), 'FM999,999,999') || ' ₪' || v_pdi || '.'
      else 'אין חוב מעל ' || v_lri || '60' || v_pdi || ' יום; יתרת-החוב הפתוחה עומדת על '
        || v_lri || to_char(round(v_open_sum), 'FM999,999,999') || ' ₪' || v_pdi || '.' end,$o2$, $n2$|| ', אצל ' || coalesce(v_oldest_name, '—') || '.'
  else 'אין חוב מעל ' || v_lri || '60' || v_pdi || ' יום.' end,$n2$);
  if (length(v_def) - length(replace(v_def, $o3$'window', 'נכון להיום · אינו מושפע ממסנן התקופה',$o3$, ''))) <> length($o3$'window', 'נכון להיום · אינו מושפע ממסנן התקופה',$o3$) then
    raise exception 'm11 text report_m07_finance_overview #3: not exactly once'; end if;
  v_def := replace(v_def, $o3$'window', 'נכון להיום · אינו מושפע ממסנן התקופה',$o3$, $n3$'window', 'נכון להיום',$n3$);
  if (length(v_def) - length(replace(v_def, $o4$'sub', v_lri || v_open_n || v_pdi
               || case when v_open_n = 1 then ' חשבונית פתוחה' else ' חשבוניות פתוחות' end,$o4$, ''))) <> length($o4$'sub', v_lri || v_open_n || v_pdi
               || case when v_open_n = 1 then ' חשבונית פתוחה' else ' חשבוניות פתוחות' end,$o4$) then
    raise exception 'm11 text report_m07_finance_overview #4: not exactly once'; end if;
  v_def := replace(v_def, $o4$'sub', v_lri || v_open_n || v_pdi
               || case when v_open_n = 1 then ' חשבונית פתוחה' else ' חשבוניות פתוחות' end,$o4$, $n4$'sub', null,$n4$);
  if (length(v_def) - length(replace(v_def, $o5$' · הערכה לפי התנהגות-תשלום היסטורית, לא התחייבות של הלקוח'$o5$, ''))) <> length($o5$' · הערכה לפי התנהגות-תשלום היסטורית, לא התחייבות של הלקוח'$o5$) then
    raise exception 'm11 text report_m07_finance_overview #5: not exactly once'; end if;
  v_def := replace(v_def, $o5$' · הערכה לפי התנהגות-תשלום היסטורית, לא התחייבות של הלקוח'$o5$, $n5$' · הערכה, לא התחייבות'$n5$);
  if (length(v_def) - length(replace(v_def, $o6$'אינה אותה נוסחה — השוואה רטרוספקטיבית; התחזית של לפני חודש לא שוחזרה'$o6$, ''))) <> length($o6$'אינה אותה נוסחה — השוואה רטרוספקטיבית; התחזית של לפני חודש לא שוחזרה'$o6$) then
    raise exception 'm11 text report_m07_finance_overview #6: not exactly once'; end if;
  v_def := replace(v_def, $o6$'אינה אותה נוסחה — השוואה רטרוספקטיבית; התחזית של לפני חודש לא שוחזרה'$o6$, $n6$'לא אותה נוסחה'$n6$);
  if (length(v_def) - length(replace(v_def, $o7$'העמודה האחרונה בגרף היא נכון ל-' || v_lri || to_char(v_to, 'DD/MM') || v_pdi || ' ואינה סוף-חודש.',
        'יתרת-החוב, "צפוי להיכנס" וטבלת-הישנות הן צילום-רגע נכון להיום, ואינן זזות עם מסנן התקופה.'),$o7$, ''))) <> length($o7$'העמודה האחרונה בגרף היא נכון ל-' || v_lri || to_char(v_to, 'DD/MM') || v_pdi || ' ואינה סוף-חודש.',
        'יתרת-החוב, "צפוי להיכנס" וטבלת-הישנות הן צילום-רגע נכון להיום, ואינן זזות עם מסנן התקופה.'),$o7$) then
    raise exception 'm11 text report_m07_finance_overview #7: not exactly once'; end if;
  v_def := replace(v_def, $o7$'העמודה האחרונה בגרף היא נכון ל-' || v_lri || to_char(v_to, 'DD/MM') || v_pdi || ' ואינה סוף-חודש.',
        'יתרת-החוב, "צפוי להיכנס" וטבלת-הישנות הן צילום-רגע נכון להיום, ואינן זזות עם מסנן התקופה.'),$o7$, $n7$'העמודה האחרונה בגרף היא נכון ל-' || v_lri || to_char(v_to, 'DD/MM') || v_pdi || ' ואינה סוף-חודש.'),$n7$);
  execute v_def;
end $m11$;

-- ═══ report_m08_profitability — 7 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m08_profitability';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'label', 'אוכלוסייה: אירועים שהתקיימו ויצאה להם חשבונית — פרויקט הסתיים · ממתין לסגירה · '$o0$, ''))) <> length($o0$'label', 'אוכלוסייה: אירועים שהתקיימו ויצאה להם חשבונית — פרויקט הסתיים · ממתין לסגירה · '$o0$) then
    raise exception 'm11 text report_m08_profitability #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'label', 'אוכלוסייה: אירועים שהתקיימו ויצאה להם חשבונית — פרויקט הסתיים · ממתין לסגירה · '$o0$, $n0$'summary', v_lri || v_n || v_pdi || ' פרויקטים שהתקיימו וחויבו',
      'label', 'אוכלוסייה: אירועים שהתקיימו ויצאה להם חשבונית — פרויקט הסתיים · ממתין לסגירה · '$n0$);
  if (length(v_def) - length(replace(v_def, $o1$|| ' מעל התכנון); בסך-הכול חרגו ' || v_lri || v_over || v_pdi || ' פרויקטים ב-'
        || v_lri || to_char(round(v_over_sum), 'FM999,999,999') || ' ₪' || v_pdi || ', מול '
        || v_lri || v_prev_over || v_pdi || ' ו-'
        || v_lri || to_char(round(v_prev_sum), 'FM999,999,999') || ' ₪' || v_pdi || ' אשתקד.'$o1$, ''))) <> length($o1$|| ' מעל התכנון); בסך-הכול חרגו ' || v_lri || v_over || v_pdi || ' פרויקטים ב-'
        || v_lri || to_char(round(v_over_sum), 'FM999,999,999') || ' ₪' || v_pdi || ', מול '
        || v_lri || v_prev_over || v_pdi || ' ו-'
        || v_lri || to_char(round(v_prev_sum), 'FM999,999,999') || ' ₪' || v_pdi || ' אשתקד.'$o1$) then
    raise exception 'm11 text report_m08_profitability #1: not exactly once'; end if;
  v_def := replace(v_def, $o1$|| ' מעל התכנון); בסך-הכול חרגו ' || v_lri || v_over || v_pdi || ' פרויקטים ב-'
        || v_lri || to_char(round(v_over_sum), 'FM999,999,999') || ' ₪' || v_pdi || ', מול '
        || v_lri || v_prev_over || v_pdi || ' ו-'
        || v_lri || to_char(round(v_prev_sum), 'FM999,999,999') || ' ₪' || v_pdi || ' אשתקד.'$o1$, $n1$|| ' מעל התכנון).'$n1$);
  if (length(v_def) - length(replace(v_def, $o2$'sub', 'אירועים שהתקיימו ויצאה להם חשבונית',$o2$, ''))) <> length($o2$'sub', 'אירועים שהתקיימו ויצאה להם חשבונית',$o2$) then
    raise exception 'm11 text report_m08_profitability #2: not exactly once'; end if;
  v_def := replace(v_def, $o2$'sub', 'אירועים שהתקיימו ויצאה להם חשבונית',$o2$, $n2$'sub', null,$n2$);
  if (length(v_def) - length(replace(v_def, $o3$'note', v_lri || to_char(round(100.0 * v_prev_over / nullif(v_prev_n, 0), 1), 'FM990.0')
                  || '%' || v_pdi || ' מהאירועים',$o3$, ''))) <> length($o3$'note', v_lri || to_char(round(100.0 * v_prev_over / nullif(v_prev_n, 0), 1), 'FM990.0')
                  || '%' || v_pdi || ' מהאירועים',$o3$) then
    raise exception 'm11 text report_m08_profitability #3: not exactly once'; end if;
  v_def := replace(v_def, $o3$'note', v_lri || to_char(round(100.0 * v_prev_over / nullif(v_prev_n, 0), 1), 'FM990.0')
                  || '%' || v_pdi || ' מהאירועים',$o3$, $n3$'note', null,$n3$);
  if (length(v_def) - length(replace(v_def, $o4$'חריגה כלפי-מעלה בלבד — חיסכון בפרויקט אחד אינו מקזז חריגה באחר'$o4$, ''))) <> length($o4$'חריגה כלפי-מעלה בלבד — חיסכון בפרויקט אחד אינו מקזז חריגה באחר'$o4$) then
    raise exception 'm11 text report_m08_profitability #4: not exactly once'; end if;
  v_def := replace(v_def, $o4$'חריגה כלפי-מעלה בלבד — חיסכון בפרויקט אחד אינו מקזז חריגה באחר'$o4$, $n4$'חריגה כלפי-מעלה בלבד'$n4$);
  if (length(v_def) - length(replace(v_def, $o5$'sub', 'סך הרווח חלקי סך ההכנסה, על אותה אוכלוסייה',$o5$, ''))) <> length($o5$'sub', 'סך הרווח חלקי סך ההכנסה, על אותה אוכלוסייה',$o5$) then
    raise exception 'm11 text report_m08_profitability #5: not exactly once'; end if;
  v_def := replace(v_def, $o5$'sub', 'סך הרווח חלקי סך ההכנסה, על אותה אוכלוסייה',$o5$, $n5$'sub', null,$n5$);
  if (length(v_def) - length(replace(v_def, $o6$'sub', 'החציון של כל ' || v_lri || v_n || v_pdi || ' הפרויקטים בתקופה — חצי מעליו וחצי מתחתיו',$o6$, ''))) <> length($o6$'sub', 'החציון של כל ' || v_lri || v_n || v_pdi || ' הפרויקטים בתקופה — חצי מעליו וחצי מתחתיו',$o6$) then
    raise exception 'm11 text report_m08_profitability #6: not exactly once'; end if;
  v_def := replace(v_def, $o6$'sub', 'החציון של כל ' || v_lri || v_n || v_pdi || ' הפרויקטים בתקופה — חצי מעליו וחצי מתחתיו',$o6$, $n6$'sub', null,$n6$);
  execute v_def;
end $m11$;

-- ═══ report_m09_aging — 8 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m09_aging';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'label', 'אוכלוסייה: חשבוניות שנשלחו, טרם שולמו ולא נמחקו כחוב-אבוד · הוצאו: חוב אבוד ('$o0$, ''))) <> length($o0$'label', 'אוכלוסייה: חשבוניות שנשלחו, טרם שולמו ולא נמחקו כחוב-אבוד · הוצאו: חוב אבוד ('$o0$) then
    raise exception 'm11 text report_m09_aging #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'label', 'אוכלוסייה: חשבוניות שנשלחו, טרם שולמו ולא נמחקו כחוב-אבוד · הוצאו: חוב אבוד ('$o0$, $n0$'summary', v_lri || v_total_n || v_pdi || ' חשבוניות פתוחות',
      'label', 'אוכלוסייה: חשבוניות שנשלחו, טרם שולמו ולא נמחקו כחוב-אבוד · הוצאו: חוב אבוד ('$n0$);
  if (length(v_def) - length(replace(v_def, $o1$' · נכון להיום — זהו צילום-רגע ולא סיכום-תקופה, ואינו מושפע ממסנן התקופה. '$o1$, ''))) <> length($o1$' · נכון להיום — זהו צילום-רגע ולא סיכום-תקופה, ואינו מושפע ממסנן התקופה. '$o1$) then
    raise exception 'm11 text report_m09_aging #1: not exactly once'; end if;
  v_def := replace(v_def, $o1$' · נכון להיום — זהו צילום-רגע ולא סיכום-תקופה, ואינו מושפע ממסנן התקופה. '$o1$, $n1$' · נכון להיום. '$n1$);
  if position($o2$'נכון להיום · אינו מושפע ממסנן התקופה'$o2$ in v_def) = 0 then raise exception 'm11 text report_m09_aging #2 not found'; end if;
  v_def := replace(v_def, $o2$'נכון להיום · אינו מושפע ממסנן התקופה'$o2$, $n2$'נכון להיום'$n2$);
  if position($o3$'כל הזמנים · אינו מושפע ממסנן התקופה'$o3$ in v_def) = 0 then raise exception 'm11 text report_m09_aging #3 not found'; end if;
  v_def := replace(v_def, $o3$'כל הזמנים · אינו מושפע ממסנן התקופה'$o3$, $n3$'כל הזמנים'$n3$);
  if position($o4$' חשבוניות ששולמו, כל הזמנים · אינו '
               || v_lri || 'DSO' || v_pdi,$o4$ in v_def) = 0 then raise exception 'm11 text report_m09_aging #4 not found'; end if;
  v_def := replace(v_def, $o4$' חשבוניות ששולמו, כל הזמנים · אינו '
               || v_lri || 'DSO' || v_pdi,$o4$, $n4$' חשבוניות ששולמו',$n4$);
  if (length(v_def) - length(replace(v_def, $o5$v_chart_note :=
    'השאלה שהעמודות עונות עליה: כמה כסף שכבר איחר יש לנו, וכמה זמן הוא כבר מחכה? '
    || 'כל עמודה היא מדרג של איחור — כמה ימים עברו מאז שהחשבונית הייתה אמורה להשתלם — '
    || 'והצבעים שבתוכה מפצלים את אותו סכום לפי סוג-הלקוח. '
    || v_lri || '1–30' || v_pdi || ' — עבר מועד התשלום, ומחכה עד חודש; תזכורת רגילה: '
    || coalesce(v_bkt -> 'd1_30' ->> 'amt', '—') || ' ב-'
    || coalesce(v_bkt -> 'd1_30' ->> 'cnt', '—') || ' חשבוניות. '
    || v_lri || '31–60' || v_pdi || ' — מחכה בין חודש לחודשיים; כאן מתחילים להתקשר: '
    || coalesce(v_bkt -> 'd31_60' ->> 'amt', '—') || ' ב-'
    || coalesce(v_bkt -> 'd31_60' ->> 'cnt', '—') || ' חשבוניות. '
    || v_lri || '61–90' || v_pdi || ' — מחכה בין חודשיים לשלושה; דורש טיפול אישי: '
    || coalesce(v_bkt -> 'd61_90' ->> 'amt', '—') || ' ב-'
    || coalesce(v_bkt -> 'd61_90' ->> 'cnt', '—') || ' חשבוניות. '
    || v_lri || '90+' || v_pdi || ' — מחכה מעל שלושה חודשים, והסיכון שלא ייגבה הוא הגבוה ביותר: '
    || coalesce(v_bkt -> 'd90p' ->> 'amt', '—') || ' ב-'
    || coalesce(v_bkt -> 'd90p' ->> 'cnt', '—') || ' חשבוניות. '
    || 'שוטף — עוד לא הגיע מועד התשלום; הכסף לא מאחר, פשוט טרם הגיע תורו, ולכן הוא אינו '
    || 'בגרף אלא באריח שלצידו: ' || coalesce(v_bkt -> 'current' ->> 'amt', '—') || ' ב-'
    || coalesce(v_bkt -> 'current' ->> 'cnt', '—') || ' חשבוניות. '
    || 'גובה העמודה = הסכום שממתין באותו מדרג; המספר שמתחת לשם המדרג = כמה חשבוניות.';$o5$, ''))) <> length($o5$v_chart_note :=
    'השאלה שהעמודות עונות עליה: כמה כסף שכבר איחר יש לנו, וכמה זמן הוא כבר מחכה? '
    || 'כל עמודה היא מדרג של איחור — כמה ימים עברו מאז שהחשבונית הייתה אמורה להשתלם — '
    || 'והצבעים שבתוכה מפצלים את אותו סכום לפי סוג-הלקוח. '
    || v_lri || '1–30' || v_pdi || ' — עבר מועד התשלום, ומחכה עד חודש; תזכורת רגילה: '
    || coalesce(v_bkt -> 'd1_30' ->> 'amt', '—') || ' ב-'
    || coalesce(v_bkt -> 'd1_30' ->> 'cnt', '—') || ' חשבוניות. '
    || v_lri || '31–60' || v_pdi || ' — מחכה בין חודש לחודשיים; כאן מתחילים להתקשר: '
    || coalesce(v_bkt -> 'd31_60' ->> 'amt', '—') || ' ב-'
    || coalesce(v_bkt -> 'd31_60' ->> 'cnt', '—') || ' חשבוניות. '
    || v_lri || '61–90' || v_pdi || ' — מחכה בין חודשיים לשלושה; דורש טיפול אישי: '
    || coalesce(v_bkt -> 'd61_90' ->> 'amt', '—') || ' ב-'
    || coalesce(v_bkt -> 'd61_90' ->> 'cnt', '—') || ' חשבוניות. '
    || v_lri || '90+' || v_pdi || ' — מחכה מעל שלושה חודשים, והסיכון שלא ייגבה הוא הגבוה ביותר: '
    || coalesce(v_bkt -> 'd90p' ->> 'amt', '—') || ' ב-'
    || coalesce(v_bkt -> 'd90p' ->> 'cnt', '—') || ' חשבוניות. '
    || 'שוטף — עוד לא הגיע מועד התשלום; הכסף לא מאחר, פשוט טרם הגיע תורו, ולכן הוא אינו '
    || 'בגרף אלא באריח שלצידו: ' || coalesce(v_bkt -> 'current' ->> 'amt', '—') || ' ב-'
    || coalesce(v_bkt -> 'current' ->> 'cnt', '—') || ' חשבוניות. '
    || 'גובה העמודה = הסכום שממתין באותו מדרג; המספר שמתחת לשם המדרג = כמה חשבוניות.';$o5$) then
    raise exception 'm11 text report_m09_aging #5: not exactly once'; end if;
  v_def := replace(v_def, $o5$v_chart_note :=
    'השאלה שהעמודות עונות עליה: כמה כסף שכבר איחר יש לנו, וכמה זמן הוא כבר מחכה? '
    || 'כל עמודה היא מדרג של איחור — כמה ימים עברו מאז שהחשבונית הייתה אמורה להשתלם — '
    || 'והצבעים שבתוכה מפצלים את אותו סכום לפי סוג-הלקוח. '
    || v_lri || '1–30' || v_pdi || ' — עבר מועד התשלום, ומחכה עד חודש; תזכורת רגילה: '
    || coalesce(v_bkt -> 'd1_30' ->> 'amt', '—') || ' ב-'
    || coalesce(v_bkt -> 'd1_30' ->> 'cnt', '—') || ' חשבוניות. '
    || v_lri || '31–60' || v_pdi || ' — מחכה בין חודש לחודשיים; כאן מתחילים להתקשר: '
    || coalesce(v_bkt -> 'd31_60' ->> 'amt', '—') || ' ב-'
    || coalesce(v_bkt -> 'd31_60' ->> 'cnt', '—') || ' חשבוניות. '
    || v_lri || '61–90' || v_pdi || ' — מחכה בין חודשיים לשלושה; דורש טיפול אישי: '
    || coalesce(v_bkt -> 'd61_90' ->> 'amt', '—') || ' ב-'
    || coalesce(v_bkt -> 'd61_90' ->> 'cnt', '—') || ' חשבוניות. '
    || v_lri || '90+' || v_pdi || ' — מחכה מעל שלושה חודשים, והסיכון שלא ייגבה הוא הגבוה ביותר: '
    || coalesce(v_bkt -> 'd90p' ->> 'amt', '—') || ' ב-'
    || coalesce(v_bkt -> 'd90p' ->> 'cnt', '—') || ' חשבוניות. '
    || 'שוטף — עוד לא הגיע מועד התשלום; הכסף לא מאחר, פשוט טרם הגיע תורו, ולכן הוא אינו '
    || 'בגרף אלא באריח שלצידו: ' || coalesce(v_bkt -> 'current' ->> 'amt', '—') || ' ב-'
    || coalesce(v_bkt -> 'current' ->> 'cnt', '—') || ' חשבוניות. '
    || 'גובה העמודה = הסכום שממתין באותו מדרג; המספר שמתחת לשם המדרג = כמה חשבוניות.';$o5$, $n5$v_chart_note := 'העמודות הן החוב שכבר איחר, לפי ותק; חוב שמועדו טרם הגיע מופיע באריח שלצד הגרף.';$n5$);
  if (length(v_def) - length(replace(v_def, $o6$jsonb_build_object('bucket', b.l, 'bucket_key', b.k,$o6$, ''))) <> length($o6$jsonb_build_object('bucket', b.l, 'bucket_key', b.k,$o6$) then
    raise exception 'm11 text report_m09_aging #6: not exactly once'; end if;
  v_def := replace(v_def, $o6$jsonb_build_object('bucket', b.l, 'bucket_key', b.k,$o6$, $n6$jsonb_build_object('bucket', b.l, 'bucket_key', b.k, 'drill_key', jsonb_build_object('bucket', b.k),$n6$);
  if (length(v_def) - length(replace(v_def, $o7$|| v_lri || coalesce(to_char(v_oldest_sent, 'DD/MM/YYYY'), '—') || v_pdi || '.',
        'כל מספרי הדף הם צילום-רגע נכון להיום; מסנן-התקופה אינו מזיז אותם.'),$o7$, ''))) <> length($o7$|| v_lri || coalesce(to_char(v_oldest_sent, 'DD/MM/YYYY'), '—') || v_pdi || '.',
        'כל מספרי הדף הם צילום-רגע נכון להיום; מסנן-התקופה אינו מזיז אותם.'),$o7$) then
    raise exception 'm11 text report_m09_aging #7: not exactly once'; end if;
  v_def := replace(v_def, $o7$|| v_lri || coalesce(to_char(v_oldest_sent, 'DD/MM/YYYY'), '—') || v_pdi || '.',
        'כל מספרי הדף הם צילום-רגע נכון להיום; מסנן-התקופה אינו מזיז אותם.'),$o7$, $n7$|| v_lri || coalesce(to_char(v_oldest_sent, 'DD/MM/YYYY'), '—') || v_pdi || '.'),$n7$);
  execute v_def;
end $m11$;

-- ═══ report_m12_equipment — 4 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m12_equipment';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'label', 'אוכלוסייה: כל ' || v_lri || to_char(v_total_rows, 'FM999,999,999') || v_pdi$o0$, ''))) <> length($o0$'label', 'אוכלוסייה: כל ' || v_lri || to_char(v_total_rows, 'FM999,999,999') || v_pdi$o0$) then
    raise exception 'm11 text report_m12_equipment #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'label', 'אוכלוסייה: כל ' || v_lri || to_char(v_total_rows, 'FM999,999,999') || v_pdi$o0$, $n0$'summary', v_lri || to_char(v_total_rows, 'FM999,999,999') || v_pdi || ' שורות ציוד',
      'label', 'אוכלוסייה: כל ' || v_lri || to_char(v_total_rows, 'FM999,999,999') || v_pdi$n0$);
  if (length(v_def) - length(replace(v_def, $o1$'sub', v_lri || v_rows_window || v_pdi
               || case when v_rows_window = 1 then ' שורת-לוגיסטיקה בתקופה' else ' שורות-לוגיסטיקה בתקופה' end,$o1$, ''))) <> length($o1$'sub', v_lri || v_rows_window || v_pdi
               || case when v_rows_window = 1 then ' שורת-לוגיסטיקה בתקופה' else ' שורות-לוגיסטיקה בתקופה' end,$o1$) then
    raise exception 'm11 text report_m12_equipment #1: not exactly once'; end if;
  v_def := replace(v_def, $o1$'sub', v_lri || v_rows_window || v_pdi
               || case when v_rows_window = 1 then ' שורת-לוגיסטיקה בתקופה' else ' שורות-לוגיסטיקה בתקופה' end,$o1$, $n1$'sub', null,$n1$);
  if (length(v_def) - length(replace(v_def, $o2$'sub', 'סכום ' || v_lri || v_sku_n || v_pdi || ' המוצרים בטבלה למטה',$o2$, ''))) <> length($o2$'sub', 'סכום ' || v_lri || v_sku_n || v_pdi || ' המוצרים בטבלה למטה',$o2$) then
    raise exception 'm11 text report_m12_equipment #2: not exactly once'; end if;
  v_def := replace(v_def, $o2$'sub', 'סכום ' || v_lri || v_sku_n || v_pdi || ' המוצרים בטבלה למטה',$o2$, $n2$'sub', null,$n2$);
  if (length(v_def) - length(replace(v_def, $o3$' — בשאר, "הגיע בפועל" הועתק מהמתוכנן ולא נמדד.',
        v_lri || v_nosrc_n || v_pdi
          || case when v_nosrc_n = 1 then ' שורת ציוד ללא מקור-עלות · כ-' else ' שורות ציוד ללא מקור-עלות · כ-' end
          || v_lri || to_char(round(v_nosrc_sum), 'FM999,999,999') || ' ₪' || v_pdi
          || ' — מחירן מוערך לפי ממוצע-המוצר ואינו נמדד.',
        '"כמות להזמנה" היא תקרה עליונה: יש להפחית ממנה הזמנות-רכש שכבר יצאו.'),$o3$, ''))) <> length($o3$' — בשאר, "הגיע בפועל" הועתק מהמתוכנן ולא נמדד.',
        v_lri || v_nosrc_n || v_pdi
          || case when v_nosrc_n = 1 then ' שורת ציוד ללא מקור-עלות · כ-' else ' שורות ציוד ללא מקור-עלות · כ-' end
          || v_lri || to_char(round(v_nosrc_sum), 'FM999,999,999') || ' ₪' || v_pdi
          || ' — מחירן מוערך לפי ממוצע-המוצר ואינו נמדד.',
        '"כמות להזמנה" היא תקרה עליונה: יש להפחית ממנה הזמנות-רכש שכבר יצאו.'),$o3$) then
    raise exception 'm11 text report_m12_equipment #3: not exactly once'; end if;
  v_def := replace(v_def, $o3$' — בשאר, "הגיע בפועל" הועתק מהמתוכנן ולא נמדד.',
        v_lri || v_nosrc_n || v_pdi
          || case when v_nosrc_n = 1 then ' שורת ציוד ללא מקור-עלות · כ-' else ' שורות ציוד ללא מקור-עלות · כ-' end
          || v_lri || to_char(round(v_nosrc_sum), 'FM999,999,999') || ' ₪' || v_pdi
          || ' — מחירן מוערך לפי ממוצע-המוצר ואינו נמדד.',
        '"כמות להזמנה" היא תקרה עליונה: יש להפחית ממנה הזמנות-רכש שכבר יצאו.'),$o3$, $n3$' — בשאר, "הגיע בפועל" הועתק מהמתוכנן ולא נמדד.'),$n3$);
  execute v_def;
end $m11$;

-- ═══ report_m14_hostess_overview — 3 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m14_hostess_overview';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'label', 'אוכלוסייה: שיבוצים שסומנה בהם נוכחות, באירוע שכבר התקיים ובפרויקט שלא בוטל · n=' ||$o0$, ''))) <> length($o0$'label', 'אוכלוסייה: שיבוצים שסומנה בהם נוכחות, באירוע שכבר התקיים ובפרויקט שלא בוטל · n=' ||$o0$) then
    raise exception 'm11 text report_m14_hostess_overview #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'label', 'אוכלוסייה: שיבוצים שסומנה בהם נוכחות, באירוע שכבר התקיים ובפרויקט שלא בוטל · n=' ||$o0$, $n0$'summary', to_char(coalesce(v_pop_n, 0), 'FM999,999,999') || ' שיבוצים · ' || to_char(coalesce(v_pop_hosts, 0), 'FM999,999,999') || ' דיילות',
      'label', 'אוכלוסייה: שיבוצים שסומנה בהם נוכחות, באירוע שכבר התקיים ובפרויקט שלא בוטל · n=' ||$n0$);
  if (length(v_def) - length(replace(v_def, $o1$if p_customer_id is not null then
    v_notes := v_notes || to_jsonb(
      'הדף אינו מושפע ממסנן הלקוח — ציון-האמינות והספים נמדדים מול ממוצע כלל המאגר, וחתך לפי לקוח היה מגדיר מחדש את הממוצע עצמו.'::text);
  end if;$o1$, ''))) <> length($o1$if p_customer_id is not null then
    v_notes := v_notes || to_jsonb(
      'הדף אינו מושפע ממסנן הלקוח — ציון-האמינות והספים נמדדים מול ממוצע כלל המאגר, וחתך לפי לקוח היה מגדיר מחדש את הממוצע עצמו.'::text);
  end if;$o1$) then
    raise exception 'm11 text report_m14_hostess_overview #1: not exactly once'; end if;
  v_def := replace(v_def, $o1$if p_customer_id is not null then
    v_notes := v_notes || to_jsonb(
      'הדף אינו מושפע ממסנן הלקוח — ציון-האמינות והספים נמדדים מול ממוצע כלל המאגר, וחתך לפי לקוח היה מגדיר מחדש את הממוצע עצמו.'::text);
  end if;$o1$, $n1$-- ✏️ פזה ב׳ 23/09/2026: שורת-המסננים אומרת "לקוח · כל הלקוחות"; הסייג ירד.$n1$);
  if (length(v_def) - length(replace(v_def, $o2$v_notes := v_notes || to_jsonb(
    ('אריח "דיילות אדומות" נמדד תמיד על 12 החודשים האחרונים ואינו זז עם מסנן התקופה — בחודש גרוע במיוחד כל הדיילות היו נראות מסתדרות, וגם ממוצע החברה היה נע איתן. שאר האריחים בדף כן זזים עם המסנן.')::text);$o2$, ''))) <> length($o2$v_notes := v_notes || to_jsonb(
    ('אריח "דיילות אדומות" נמדד תמיד על 12 החודשים האחרונים ואינו זז עם מסנן התקופה — בחודש גרוע במיוחד כל הדיילות היו נראות מסתדרות, וגם ממוצע החברה היה נע איתן. שאר האריחים בדף כן זזים עם המסנן.')::text);$o2$) then
    raise exception 'm11 text report_m14_hostess_overview #2: not exactly once'; end if;
  v_def := replace(v_def, $o2$v_notes := v_notes || to_jsonb(
    ('אריח "דיילות אדומות" נמדד תמיד על 12 החודשים האחרונים ואינו זז עם מסנן התקופה — בחודש גרוע במיוחד כל הדיילות היו נראות מסתדרות, וגם ממוצע החברה היה נע איתן. שאר האריחים בדף כן זזים עם המסנן.')::text);$o2$, $n2$-- ✏️ פזה ב׳ 23/09/2026: חלון-האריח ("חלון קבוע · 12 חודשים") אומר זאת; ההערה ירדה.$n2$);
  execute v_def;
end $m11$;

-- ═══ report_m15_reliability — 6 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m15_reliability';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'label', 'אוכלוסייה: דיילות עם ' || coalesce(to_char(v_min_sample, 'FM999,999,999'), '—') ||$o0$, ''))) <> length($o0$'label', 'אוכלוסייה: דיילות עם ' || coalesce(to_char(v_min_sample, 'FM999,999,999'), '—') ||$o0$) then
    raise exception 'm11 text report_m15_reliability #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'label', 'אוכלוסייה: דיילות עם ' || coalesce(to_char(v_min_sample, 'FM999,999,999'), '—') ||$o0$, $n0$'summary', to_char(coalesce(v_in_report, 0), 'FM999,999,999') || ' דיילות עם ' || coalesce(to_char(v_min_sample, 'FM999,999,999'), '—') || ' משמרות ומעלה',
      'label', 'אוכלוסייה: דיילות עם ' || coalesce(to_char(v_min_sample, 'FM999,999,999'), '—') ||$n0$);
  if (length(v_def) - length(replace(v_def, $o1$'label', 'חלון קבוע · 12 החודשים האחרונים'$o1$, ''))) <> length($o1$'label', 'חלון קבוע · 12 החודשים האחרונים'$o1$) then
    raise exception 'm11 text report_m15_reliability #1: not exactly once'; end if;
  v_def := replace(v_def, $o1$'label', 'חלון קבוע · 12 החודשים האחרונים'$o1$, $n1$'label', '12 החודשים האחרונים'$n1$);
  if (length(v_def) - length(replace(v_def, $o2$'customer_filter_ignored', true,$o2$, ''))) <> length($o2$'customer_filter_ignored', true,$o2$) then
    raise exception 'm11 text report_m15_reliability #2: not exactly once'; end if;
  v_def := replace(v_def, $o2$'customer_filter_ignored', true,$o2$, $n2$'customer_filter_ignored', true,
      'period_filter_ignored', true,$n2$);
  if (length(v_def) - length(replace(v_def, $o3$if p_from is not null or p_to is not null then
    v_notes := v_notes || to_jsonb(
      'החלון כאן קבוע על 12 חודשים ואינו זז עם מסנן התקופה — בחודש גרוע במיוחד כל הדיילות היו נראות מסתדרות, וגם ממוצע החברה היה נע איתן.'::text);
  end if;$o3$, ''))) <> length($o3$if p_from is not null or p_to is not null then
    v_notes := v_notes || to_jsonb(
      'החלון כאן קבוע על 12 חודשים ואינו זז עם מסנן התקופה — בחודש גרוע במיוחד כל הדיילות היו נראות מסתדרות, וגם ממוצע החברה היה נע איתן.'::text);
  end if;$o3$) then
    raise exception 'm11 text report_m15_reliability #3: not exactly once'; end if;
  v_def := replace(v_def, $o3$if p_from is not null or p_to is not null then
    v_notes := v_notes || to_jsonb(
      'החלון כאן קבוע על 12 חודשים ואינו זז עם מסנן התקופה — בחודש גרוע במיוחד כל הדיילות היו נראות מסתדרות, וגם ממוצע החברה היה נע איתן.'::text);
  end if;$o3$, $n3$-- ✏️ פזה ב׳ 23/09/2026: שורת-המסננים אומרת "תקופה · 12 החודשים האחרונים"; הסייג ירד.$n3$);
  if (length(v_def) - length(replace(v_def, $o4$if p_customer_id is not null then
    v_notes := v_notes || to_jsonb(
      'הדף אינו מושפע ממסנן הלקוח — הציון והספים נמדדים מול ממוצע כלל המאגר.'::text);
  end if;$o4$, ''))) <> length($o4$if p_customer_id is not null then
    v_notes := v_notes || to_jsonb(
      'הדף אינו מושפע ממסנן הלקוח — הציון והספים נמדדים מול ממוצע כלל המאגר.'::text);
  end if;$o4$) then
    raise exception 'm11 text report_m15_reliability #4: not exactly once'; end if;
  v_def := replace(v_def, $o4$if p_customer_id is not null then
    v_notes := v_notes || to_jsonb(
      'הדף אינו מושפע ממסנן הלקוח — הציון והספים נמדדים מול ממוצע כלל המאגר.'::text);
  end if;$o4$, $n4$-- ✏️ פזה ב׳ 23/09/2026: שורת-המסננים אומרת "לקוח · כל הלקוחות"; הסייג ירד.$n4$);
  if position($o5$'window', 'חלון קבוע · 12 חודשים',$o5$ in v_def) = 0 then raise exception 'm11 text report_m15_reliability #5 not found'; end if;
  v_def := replace(v_def, $o5$'window', 'חלון קבוע · 12 חודשים',$o5$, $n5$'window', null,$n5$);
  execute v_def;
end $m11$;

-- ═══ report_m16_quality_cost — 3 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m16_quality_cost';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'label', 'אוכלוסייה: דיילות פעילות בלבד — n=' ||$o0$, ''))) <> length($o0$'label', 'אוכלוסייה: דיילות פעילות בלבד — n=' ||$o0$) then
    raise exception 'm11 text report_m16_quality_cost #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'label', 'אוכלוסייה: דיילות פעילות בלבד — n=' ||$o0$, $n0$'summary', to_char(coalesce(v_active, 0), 'FM999,999,999') || ' דיילות פעילות · מתוך ' || to_char(coalesce(v_registered, 0), 'FM999,999,999'),
      'label', 'אוכלוסייה: דיילות פעילות בלבד — n=' ||$n0$);
  if (length(v_def) - length(replace(v_def, $o1$else 'להוריד את התעריף של ' || to_char(coalesce(v_expensive, 0), 'FM999,999,999') || ' הדיילות שמעל חציון-המאגר בדירוג 3 ומטה, או להפסיק לשלוח אותן; ובמקביל לדרג את ' ||
           to_char(coalesce(v_no_rating, 0), 'FM999,999,999') || ' הפעילות שאין להן דירוג.' end,$o1$, ''))) <> length($o1$else 'להוריד את התעריף של ' || to_char(coalesce(v_expensive, 0), 'FM999,999,999') || ' הדיילות שמעל חציון-המאגר בדירוג 3 ומטה, או להפסיק לשלוח אותן; ובמקביל לדרג את ' ||
           to_char(coalesce(v_no_rating, 0), 'FM999,999,999') || ' הפעילות שאין להן דירוג.' end,$o1$) then
    raise exception 'm11 text report_m16_quality_cost #1: not exactly once'; end if;
  v_def := replace(v_def, $o1$else 'להוריד את התעריף של ' || to_char(coalesce(v_expensive, 0), 'FM999,999,999') || ' הדיילות שמעל חציון-המאגר בדירוג 3 ומטה, או להפסיק לשלוח אותן; ובמקביל לדרג את ' ||
           to_char(coalesce(v_no_rating, 0), 'FM999,999,999') || ' הפעילות שאין להן דירוג.' end,$o1$, $n1$else 'להוריד את התעריף של ' || to_char(coalesce(v_expensive, 0), 'FM999,999,999') || ' הדיילות היקרות בדירוג 3 ומטה, ולדרג את ' ||
       to_char(coalesce(v_no_rating, 0), 'FM999,999,999') || ' שאין להן דירוג.' end,$n1$);
  if (length(v_def) - length(replace(v_def, $o2$if p_customer_id is not null then
    v_notes := v_notes || to_jsonb(
      'הדף אינו מושפע ממסנן הלקוח — התעריף והדירוג הם ערכי-היום בכרטיס הדיילת, ואין להם חתך לפי לקוח.'::text);
  end if;$o2$, ''))) <> length($o2$if p_customer_id is not null then
    v_notes := v_notes || to_jsonb(
      'הדף אינו מושפע ממסנן הלקוח — התעריף והדירוג הם ערכי-היום בכרטיס הדיילת, ואין להם חתך לפי לקוח.'::text);
  end if;$o2$) then
    raise exception 'm11 text report_m16_quality_cost #2: not exactly once'; end if;
  v_def := replace(v_def, $o2$if p_customer_id is not null then
    v_notes := v_notes || to_jsonb(
      'הדף אינו מושפע ממסנן הלקוח — התעריף והדירוג הם ערכי-היום בכרטיס הדיילת, ואין להם חתך לפי לקוח.'::text);
  end if;$o2$, $n2$-- ✏️ פזה ב׳ 23/09/2026: שורת-המסננים אומרת "לקוח · כל הלקוחות"; הסייג ירד.$n2$);
  execute v_def;
end $m11$;

-- ═══ report_m17_fairness — 8 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m17_fairness';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'label', 'אוכלוסייה: כל דיילת עם משמרת מאושרת אחת לפחות בחלון — ' ||$o0$, ''))) <> length($o0$'label', 'אוכלוסייה: כל דיילת עם משמרת מאושרת אחת לפחות בחלון — ' ||$o0$) then
    raise exception 'm11 text report_m17_fairness #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'label', 'אוכלוסייה: כל דיילת עם משמרת מאושרת אחת לפחות בחלון — ' ||$o0$, $n0$'summary', v_lri || coalesce(v_n, 0) || v_pdi || ' דיילות · ' || v_lri || to_char(coalesce(v_invites, 0), 'FM999,999') || v_pdi || ' זימונים',
      'label', 'אוכלוסייה: כל דיילת עם משמרת מאושרת אחת לפחות בחלון — ' ||$n0$);
  if (length(v_def) - length(replace(v_def, $o1$if p_customer_id is not null then
    v_notes := v_notes || to_jsonb(
      'הדף אינו מושפע ממסנן הלקוח — ההוגנות נמדדת על חלוקת המשמרות בכל המאגר.'::text);
  end if;$o1$, ''))) <> length($o1$if p_customer_id is not null then
    v_notes := v_notes || to_jsonb(
      'הדף אינו מושפע ממסנן הלקוח — ההוגנות נמדדת על חלוקת המשמרות בכל המאגר.'::text);
  end if;$o1$) then
    raise exception 'm11 text report_m17_fairness #1: not exactly once'; end if;
  v_def := replace(v_def, $o1$if p_customer_id is not null then
    v_notes := v_notes || to_jsonb(
      'הדף אינו מושפע ממסנן הלקוח — ההוגנות נמדדת על חלוקת המשמרות בכל המאגר.'::text);
  end if;$o1$, $n1$-- ✏️ פזה ב׳ 23/09/2026: שורת-המסננים אומרת "לקוח · כל הלקוחות"; הסייג ירד.$n1$);
  if (length(v_def) - length(replace(v_def, $o2$if coalesce(v_rank_total, 0) = 0 then
    v_notes := v_notes || to_jsonb(
      'אימוץ המלצת Smart Match — אין עדיין נתון: המערכת התחילה לרשום את הדרג שהמליצה רק מעכשיו, ועד שייצברו שיבוצים המדד מציג "—" ולא 0%.'::text);
  end if;$o2$, ''))) <> length($o2$if coalesce(v_rank_total, 0) = 0 then
    v_notes := v_notes || to_jsonb(
      'אימוץ המלצת Smart Match — אין עדיין נתון: המערכת התחילה לרשום את הדרג שהמליצה רק מעכשיו, ועד שייצברו שיבוצים המדד מציג "—" ולא 0%.'::text);
  end if;$o2$) then
    raise exception 'm11 text report_m17_fairness #2: not exactly once'; end if;
  v_def := replace(v_def, $o2$if coalesce(v_rank_total, 0) = 0 then
    v_notes := v_notes || to_jsonb(
      'אימוץ המלצת Smart Match — אין עדיין נתון: המערכת התחילה לרשום את הדרג שהמליצה רק מעכשיו, ועד שייצברו שיבוצים המדד מציג "—" ולא 0%.'::text);
  end if;$o2$, $n2$-- ✏️ פזה ב׳ 23/09/2026: האריח עצמו אומר "טרם נמדד"; ההערה ירדה.$n2$);
  if (length(v_def) - length(replace(v_def, $o3$'notes', v_notes || to_jsonb(
        ('זמן-התגובה נמדד מאז הזימון האחרון ולא מהראשון — שליחה חוזרת דורסת את שעת הזימון, ולכן הזמן שרואים כאן קצר מהזמן שבאמת חיכית.')::text),$o3$, ''))) <> length($o3$'notes', v_notes || to_jsonb(
        ('זמן-התגובה נמדד מאז הזימון האחרון ולא מהראשון — שליחה חוזרת דורסת את שעת הזימון, ולכן הזמן שרואים כאן קצר מהזמן שבאמת חיכית.')::text),$o3$) then
    raise exception 'm11 text report_m17_fairness #3: not exactly once'; end if;
  v_def := replace(v_def, $o3$'notes', v_notes || to_jsonb(
        ('זמן-התגובה נמדד מאז הזימון האחרון ולא מהראשון — שליחה חוזרת דורסת את שעת הזימון, ולכן הזמן שרואים כאן קצר מהזמן שבאמת חיכית.')::text),$o3$, $n3$'notes', v_notes,$n3$);
  if (length(v_def) - length(replace(v_def, $o4$then 'טרם נמדד · אין עדיין נתון: המערכת התחילה לרשום את הדרג שהמליצה רק מעכשיו, ועד שייצברו שיבוצים המדד מציג "—" ולא ' ||
                         v_lri || '0%' || v_pdi$o4$, ''))) <> length($o4$then 'טרם נמדד · אין עדיין נתון: המערכת התחילה לרשום את הדרג שהמליצה רק מעכשיו, ועד שייצברו שיבוצים המדד מציג "—" ולא ' ||
                         v_lri || '0%' || v_pdi$o4$) then
    raise exception 'm11 text report_m17_fairness #4: not exactly once'; end if;
  v_def := replace(v_def, $o4$then 'טרם נמדד · אין עדיין נתון: המערכת התחילה לרשום את הדרג שהמליצה רק מעכשיו, ועד שייצברו שיבוצים המדד מציג "—" ולא ' ||
                         v_lri || '0%' || v_pdi$o4$, $n4$then 'טרם נמדד — הרישום התחיל רק עכשיו'$n4$);
  if (length(v_def) - length(replace(v_def, $o5$'שעות · אחת מכל עשר תשובות מגיעה לאט מזה — שם יושב הכאב של איוש שנתקע, לא בחציון'$o5$, ''))) <> length($o5$'שעות · אחת מכל עשר תשובות מגיעה לאט מזה — שם יושב הכאב של איוש שנתקע, לא בחציון'$o5$) then
    raise exception 'm11 text report_m17_fairness #5: not exactly once'; end if;
  v_def := replace(v_def, $o5$'שעות · אחת מכל עשר תשובות מגיעה לאט מזה — שם יושב הכאב של איוש שנתקע, לא בחציון'$o5$, $n5$'שעות'$n5$);
  if (length(v_def) - length(replace(v_def, $o6$'חלק מהשינוי הוא שינוי-אוכלוסייה ולא שינוי-התנהגות'$o6$, ''))) <> length($o6$'חלק מהשינוי הוא שינוי-אוכלוסייה ולא שינוי-התנהגות'$o6$) then
    raise exception 'm11 text report_m17_fairness #6: not exactly once'; end if;
  v_def := replace(v_def, $o6$'חלק מהשינוי הוא שינוי-אוכלוסייה ולא שינוי-התנהגות'$o6$, $n6$null$n6$);
  if (length(v_def) - length(replace(v_def, $o7$'note', 'הקו הישר הוא חלוקה שווה לגמרי. ככל שהעקומה נופלת ממנו, החלוקה ריכוזית יותר, '
              'והשטח שביניהם הוא בדיוק מה שמדד ג''יני מודד. הדיילות מסודרות מהפחות-עמוסה '
              'משמאל לעמוסה-ביותר מימין.',$o7$, ''))) <> length($o7$'note', 'הקו הישר הוא חלוקה שווה לגמרי. ככל שהעקומה נופלת ממנו, החלוקה ריכוזית יותר, '
              'והשטח שביניהם הוא בדיוק מה שמדד ג''יני מודד. הדיילות מסודרות מהפחות-עמוסה '
              'משמאל לעמוסה-ביותר מימין.',$o7$) then
    raise exception 'm11 text report_m17_fairness #7: not exactly once'; end if;
  v_def := replace(v_def, $o7$'note', 'הקו הישר הוא חלוקה שווה לגמרי. ככל שהעקומה נופלת ממנו, החלוקה ריכוזית יותר, '
              'והשטח שביניהם הוא בדיוק מה שמדד ג''יני מודד. הדיילות מסודרות מהפחות-עמוסה '
              'משמאל לעמוסה-ביותר מימין.',$o7$, $n7$'note', 'הקו הישר הוא חלוקה שווה; ככל שהעקומה רחוקה ממנו — החלוקה ריכוזית יותר.',$n7$);
  execute v_def;
end $m11$;

-- ═══ report_m19_customers_overview — 6 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m19_customers_overview';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'label', 'אוכלוסייה: משובים שהלקוח מילא · הוצאו: משובים שנשלחו ולא נענו ('$o0$, ''))) <> length($o0$'label', 'אוכלוסייה: משובים שהלקוח מילא · הוצאו: משובים שנשלחו ולא נענו ('$o0$) then
    raise exception 'm11 text report_m19_customers_overview #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'label', 'אוכלוסייה: משובים שהלקוח מילא · הוצאו: משובים שנשלחו ולא נענו ('$o0$, $n0$'summary', v_lri || to_char(v_pop_n, 'FM999,999,999') || v_pdi || ' משובים · מתוך ' || v_lri || to_char(v_pop_sent, 'FM999,999,999') || v_pdi || ' שנשלחו',
      'label', 'אוכלוסייה: משובים שהלקוח מילא · הוצאו: משובים שנשלחו ולא נענו ('$n0$);
  if (length(v_def) - length(replace(v_def, $o1$else 'לפתוח את "שביעות רצון" ולראות מה מכעיס את ' || v_lri || to_char(v_uns_cnt, 'FM999,999,999') || v_pdi
           || ' הלקוחות הלא-מרוצים (ממוצע מתחת ל-' || v_lri || '3.5' || v_pdi || ') — הם לא הזמינו כבר '
           || v_lri || v_uns_med || v_pdi || ' ימים (חציון), מול ' || v_lri || v_sat_med || v_pdi
           || ' ימים אצל ' || v_lri || to_char(v_sat_cnt, 'FM999,999,999') || v_pdi || ' הלקוחות המרוצים (ממוצע '
           || v_lri || '4.5+' || v_pdi || ').' end,$o1$, ''))) <> length($o1$else 'לפתוח את "שביעות רצון" ולראות מה מכעיס את ' || v_lri || to_char(v_uns_cnt, 'FM999,999,999') || v_pdi
           || ' הלקוחות הלא-מרוצים (ממוצע מתחת ל-' || v_lri || '3.5' || v_pdi || ') — הם לא הזמינו כבר '
           || v_lri || v_uns_med || v_pdi || ' ימים (חציון), מול ' || v_lri || v_sat_med || v_pdi
           || ' ימים אצל ' || v_lri || to_char(v_sat_cnt, 'FM999,999,999') || v_pdi || ' הלקוחות המרוצים (ממוצע '
           || v_lri || '4.5+' || v_pdi || ').' end,$o1$) then
    raise exception 'm11 text report_m19_customers_overview #1: not exactly once'; end if;
  v_def := replace(v_def, $o1$else 'לפתוח את "שביעות רצון" ולראות מה מכעיס את ' || v_lri || to_char(v_uns_cnt, 'FM999,999,999') || v_pdi
           || ' הלקוחות הלא-מרוצים (ממוצע מתחת ל-' || v_lri || '3.5' || v_pdi || ') — הם לא הזמינו כבר '
           || v_lri || v_uns_med || v_pdi || ' ימים (חציון), מול ' || v_lri || v_sat_med || v_pdi
           || ' ימים אצל ' || v_lri || to_char(v_sat_cnt, 'FM999,999,999') || v_pdi || ' הלקוחות המרוצים (ממוצע '
           || v_lri || '4.5+' || v_pdi || ').' end,$o1$, $n1$else 'לפתוח את "שביעות רצון" — ' || v_lri || to_char(v_uns_cnt, 'FM999,999,999') || v_pdi
       || ' הלקוחות הלא-מרוצים לא הזמינו כבר ' || v_lri || v_uns_med || v_pdi || ' ימים, מול '
       || v_lri || v_sat_med || v_pdi || ' אצל המרוצים.' end,$n1$);
  if position($o2$ · אינו מושפע ממסנן התקופה$o2$ in v_def) = 0 then raise exception 'm11 text report_m19_customers_overview #2 not found'; end if;
  v_def := replace(v_def, $o2$ · אינו מושפע ממסנן התקופה$o2$, $n2$$n2$);
  if (length(v_def) - length(replace(v_def, $o3$|| to_jsonb('ארבעת האריחים נמדדים על כל הזמנים ואינם מושפעים ממסנן התקופה; הגרף והטבלה כן.'::text)
    || to_jsonb('ארבעת האריחים הם חתכים בין-לקוחיים ואינם מושפעים ממסנן הלקוח.'::text)$o3$, ''))) <> length($o3$|| to_jsonb('ארבעת האריחים נמדדים על כל הזמנים ואינם מושפעים ממסנן התקופה; הגרף והטבלה כן.'::text)
    || to_jsonb('ארבעת האריחים הם חתכים בין-לקוחיים ואינם מושפעים ממסנן הלקוח.'::text)$o3$) then
    raise exception 'm11 text report_m19_customers_overview #3: not exactly once'; end if;
  v_def := replace(v_def, $o3$|| to_jsonb('ארבעת האריחים נמדדים על כל הזמנים ואינם מושפעים ממסנן התקופה; הגרף והטבלה כן.'::text)
    || to_jsonb('ארבעת האריחים הם חתכים בין-לקוחיים ואינם מושפעים ממסנן הלקוח.'::text)$o3$, $n3$$n3$);
  if (length(v_def) - length(replace(v_def, $o4$'הדף אינו דוח-קידוח (📐13) — פרמטר הקידוח לא הופעל.'$o4$, ''))) <> length($o4$'הדף אינו דוח-קידוח (📐13) — פרמטר הקידוח לא הופעל.'$o4$) then
    raise exception 'm11 text report_m19_customers_overview #4: not exactly once'; end if;
  v_def := replace(v_def, $o4$'הדף אינו דוח-קידוח (📐13) — פרמטר הקידוח לא הופעל.'$o4$, $n4$'הדוח הזה אינו תומך בקידוח.'$n4$);
  if (length(v_def) - length(replace(v_def, $o5$'sub', 'חציון ימים מאז האירוע האחרון: לקוחות מרוצים (ממוצע 4.5+) מול לקוחות לא-מרוצים (ממוצע מתחת ל-3.5) · הבינוניים באמצע: '
               || v_lri || coalesce(v_mid_med::text, '—') || v_pdi || ' ימים',$o5$, ''))) <> length($o5$'sub', 'חציון ימים מאז האירוע האחרון: לקוחות מרוצים (ממוצע 4.5+) מול לקוחות לא-מרוצים (ממוצע מתחת ל-3.5) · הבינוניים באמצע: '
               || v_lri || coalesce(v_mid_med::text, '—') || v_pdi || ' ימים',$o5$) then
    raise exception 'm11 text report_m19_customers_overview #5: not exactly once'; end if;
  v_def := replace(v_def, $o5$'sub', 'חציון ימים מאז האירוע האחרון: לקוחות מרוצים (ממוצע 4.5+) מול לקוחות לא-מרוצים (ממוצע מתחת ל-3.5) · הבינוניים באמצע: '
               || v_lri || coalesce(v_mid_med::text, '—') || v_pdi || ' ימים',$o5$, $n5$'sub', 'ימים מאז האירוע האחרון (חציון) — מרוצים מול לא-מרוצים',$n5$);
  execute v_def;
end $m11$;

-- ═══ report_m20_satisfaction — 6 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m20_satisfaction';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'label', 'אוכלוסייה: משובים שהלקוח מילא · הוצאו: ' || v_lri || to_char(v_no_resp, 'FM999,999,999') || v_pdi$o0$, ''))) <> length($o0$'label', 'אוכלוסייה: משובים שהלקוח מילא · הוצאו: ' || v_lri || to_char(v_no_resp, 'FM999,999,999') || v_pdi$o0$) then
    raise exception 'm11 text report_m20_satisfaction #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'label', 'אוכלוסייה: משובים שהלקוח מילא · הוצאו: ' || v_lri || to_char(v_no_resp, 'FM999,999,999') || v_pdi$o0$, $n0$'summary', v_lri || to_char(v_completed, 'FM999,999,999') || v_pdi || ' משובים שמולאו · מתוך ' || v_lri || to_char(v_held, 'FM999,999,999') || v_pdi || ' אירועים',
      'label', 'אוכלוסייה: משובים שהלקוח מילא · הוצאו: ' || v_lri || to_char(v_no_resp, 'FM999,999,999') || v_pdi$n0$);
  if (length(v_def) - length(replace(v_def, $o1$then 'לפתוח את ' || v_lri || to_char(v_other_n, 'FM999,999,999') || v_pdi
             || ' המשובים שתויגו "אחר" — הם הסיבה השלילית הגדולה בתקופה, גדולה מכל הקטגוריות הקיימות יחד ('
             || v_lri || to_char(v_rest_n, 'FM999,999,999') || v_pdi || '), ואיש לא קרא את הטקסט שבהם.'$o1$, ''))) <> length($o1$then 'לפתוח את ' || v_lri || to_char(v_other_n, 'FM999,999,999') || v_pdi
             || ' המשובים שתויגו "אחר" — הם הסיבה השלילית הגדולה בתקופה, גדולה מכל הקטגוריות הקיימות יחד ('
             || v_lri || to_char(v_rest_n, 'FM999,999,999') || v_pdi || '), ואיש לא קרא את הטקסט שבהם.'$o1$) then
    raise exception 'm11 text report_m20_satisfaction #1: not exactly once'; end if;
  v_def := replace(v_def, $o1$then 'לפתוח את ' || v_lri || to_char(v_other_n, 'FM999,999,999') || v_pdi
             || ' המשובים שתויגו "אחר" — הם הסיבה השלילית הגדולה בתקופה, גדולה מכל הקטגוריות הקיימות יחד ('
             || v_lri || to_char(v_rest_n, 'FM999,999,999') || v_pdi || '), ואיש לא קרא את הטקסט שבהם.'$o1$, $n1$then 'לקרוא את ' || v_lri || to_char(v_other_n, 'FM999,999,999') || v_pdi
         || ' המשובים שתויגו "אחר" — יותר מכל הסיבות האחרות יחד, ואיש עוד לא קרא אותם.'$n1$);
  if (length(v_def) - length(replace(v_def, $o2$'filter_key', false),
      jsonb_build_object(
        'type', 'bar',
        'title', 'מה מכעיס · ' || v_lri || to_char(v_with_neg, 'FM999,999,999') || v_pdi || ' משובים סימנו סיבה שלילית',
        -- 🪤 I1 · התאום של ההערה בגרף החיובי — אותה אזהרה, מהצד השני.
        'note', 'הסולם כאן עצמאי ואינו משותף לגרף החיובי שלצידו — אורך עמודה בגרף '
                'אחד אינו מייצג את אותו מספר בגרף השני.',
        -- 🪤 I1 · `series[].format` הוא הקודם ל-`unit` בגזירת תו-הסימון
        --    ובטולטיפ, והוא היה `null`. הערכים עצמם אינם זזים.
        'series', jsonb_build_array(jsonb_build_object('key', 'n', 'label', 'משובים', 'format', 'int')),
        'data', v_neg, 'xKey', 'reason', 'domain', null, 'refLines', '[]'::jsonb,
      -- 🪤 I1 · **`chart.unit` הוא שם-פורמט של C8, לא מחרוזת-תצוגה.**
      --    ‏`ChartCard.valueFormat` מחזיר `series[0].format ?? unit` ומזין את
      --    ‏`formatAxisTick`, ו-`HebrewTooltip` מזין את `formatByType` — שניהם מצפים
      --    ל-`money|percent|int|ratio|score|days|text|date`. מחרוזת-תצוגה היא **פורמט
      --    לא-מוכר** ⇒ הציר נופל לקיבוץ-אלפים חשוף והטולטיפ ל-`text`.
      --    הכיתוב העברי נשמר ב-`unit_label` (תוספתי; **אין לו קורא היום** — מדווח).
        'unit', 'int', 'unit_label', 'משובים',
        -- 🪤 I1 · המוקאפ המאושר (`05_tab_customers_approved.html`) מצייר את שני גרפי-הסיבות
        --    **אופקית** — `aria-label` אומר *"עמודות אופקיות"* ותוויות-הקטגוריה עומדות
        --    ב-`x=129 text-anchor="end"`. שמות-הסיבות הם ביטויים עבריים בני 2–3 מילים, ובציר-X
        --    אנכי הם נחתכים. ‏`layout` הוא מפתח **תוספתי** שהמעטפת קוראת (`ChartCard.BarBody`).
        'layout', 'horizontal',
        -- ✅ **הסינון-הצולב היחיד שהמפגש שלו מדויק.** אוכלוסיית הגרף היא בדיוק
        -- אוכלוסיית הטבלה: כל שורה בטבלה סימנה סיבה שלילית אחת, וסכום העמודות
        -- (3+3+3+0+10) שווה ל-19 שורות הטבלה. **המספר שעל העמודה הוא מספר השורות**
        -- שהלחיצה תציג — וזה התנאי שמפריד בין סינון-צולב אמיתי לבין טבלה ריקה.
        -- `filter_key` הוא שם **שדה-השורה** ולא שם ה-`xKey`, והמעטפת משווה
        -- `row['negative_reason']` מול `datum['reason']` (`ReportSurface` §מפתח-הסינון ②).
        'filter_key', 'negative_reason'),
      jsonb_build_object(
        'type', 'bar',
        'title', 'שיעור המרוצים לפי שנה — אינו מושפע ממסנן התקופה',
        -- 🪤 I1 · **זה הגרף שהמדידה נקבה בו:** ציר-הערך קרא 0/25/50/75/100
        --    בלי `%`, כי `'%'` אינו שם-פורמט ו-`series[].format` היה `null`.
        'series', jsonb_build_array(jsonb_build_object('key', 'satisfied_share', 'label', 'שיעור מרוצים',
                                                      'format', 'percent')),
        'data', v_years, 'xKey', 'year',
        'domain', jsonb_build_array(0, 100), 'refLines', '[]'::jsonb, 'unit', 'percent',
        -- 🚫 **כבוי במפורש לפי הכרטיס עצמו** ① (*"לא לחיצה — הגרף מתעלם
        -- ממסנן-התקופה בכוונה, ולחיצה עליו הייתה סותרת את ההצהרה שלו"*). ההצהרה
        -- כתובה כאן ואינה נשענת על כך שהזיהוי-האוטומטי ממילא ייכשל — זיהוי-שנכשל
        -- וכיבוי-מכוון נראים זהים על המסך ושונים לגמרי בקוד.
        'filter_key', false))$o2$, ''))) <> length($o2$'filter_key', false),
      jsonb_build_object(
        'type', 'bar',
        'title', 'מה מכעיס · ' || v_lri || to_char(v_with_neg, 'FM999,999,999') || v_pdi || ' משובים סימנו סיבה שלילית',
        -- 🪤 I1 · התאום של ההערה בגרף החיובי — אותה אזהרה, מהצד השני.
        'note', 'הסולם כאן עצמאי ואינו משותף לגרף החיובי שלצידו — אורך עמודה בגרף '
                'אחד אינו מייצג את אותו מספר בגרף השני.',
        -- 🪤 I1 · `series[].format` הוא הקודם ל-`unit` בגזירת תו-הסימון
        --    ובטולטיפ, והוא היה `null`. הערכים עצמם אינם זזים.
        'series', jsonb_build_array(jsonb_build_object('key', 'n', 'label', 'משובים', 'format', 'int')),
        'data', v_neg, 'xKey', 'reason', 'domain', null, 'refLines', '[]'::jsonb,
      -- 🪤 I1 · **`chart.unit` הוא שם-פורמט של C8, לא מחרוזת-תצוגה.**
      --    ‏`ChartCard.valueFormat` מחזיר `series[0].format ?? unit` ומזין את
      --    ‏`formatAxisTick`, ו-`HebrewTooltip` מזין את `formatByType` — שניהם מצפים
      --    ל-`money|percent|int|ratio|score|days|text|date`. מחרוזת-תצוגה היא **פורמט
      --    לא-מוכר** ⇒ הציר נופל לקיבוץ-אלפים חשוף והטולטיפ ל-`text`.
      --    הכיתוב העברי נשמר ב-`unit_label` (תוספתי; **אין לו קורא היום** — מדווח).
        'unit', 'int', 'unit_label', 'משובים',
        -- 🪤 I1 · המוקאפ המאושר (`05_tab_customers_approved.html`) מצייר את שני גרפי-הסיבות
        --    **אופקית** — `aria-label` אומר *"עמודות אופקיות"* ותוויות-הקטגוריה עומדות
        --    ב-`x=129 text-anchor="end"`. שמות-הסיבות הם ביטויים עבריים בני 2–3 מילים, ובציר-X
        --    אנכי הם נחתכים. ‏`layout` הוא מפתח **תוספתי** שהמעטפת קוראת (`ChartCard.BarBody`).
        'layout', 'horizontal',
        -- ✅ **הסינון-הצולב היחיד שהמפגש שלו מדויק.** אוכלוסיית הגרף היא בדיוק
        -- אוכלוסיית הטבלה: כל שורה בטבלה סימנה סיבה שלילית אחת, וסכום העמודות
        -- (3+3+3+0+10) שווה ל-19 שורות הטבלה. **המספר שעל העמודה הוא מספר השורות**
        -- שהלחיצה תציג — וזה התנאי שמפריד בין סינון-צולב אמיתי לבין טבלה ריקה.
        -- `filter_key` הוא שם **שדה-השורה** ולא שם ה-`xKey`, והמעטפת משווה
        -- `row['negative_reason']` מול `datum['reason']` (`ReportSurface` §מפתח-הסינון ②).
        'filter_key', 'negative_reason'),
      jsonb_build_object(
        'type', 'bar',
        'title', 'שיעור המרוצים לפי שנה — אינו מושפע ממסנן התקופה',
        -- 🪤 I1 · **זה הגרף שהמדידה נקבה בו:** ציר-הערך קרא 0/25/50/75/100
        --    בלי `%`, כי `'%'` אינו שם-פורמט ו-`series[].format` היה `null`.
        'series', jsonb_build_array(jsonb_build_object('key', 'satisfied_share', 'label', 'שיעור מרוצים',
                                                      'format', 'percent')),
        'data', v_years, 'xKey', 'year',
        'domain', jsonb_build_array(0, 100), 'refLines', '[]'::jsonb, 'unit', 'percent',
        -- 🚫 **כבוי במפורש לפי הכרטיס עצמו** ① (*"לא לחיצה — הגרף מתעלם
        -- ממסנן-התקופה בכוונה, ולחיצה עליו הייתה סותרת את ההצהרה שלו"*). ההצהרה
        -- כתובה כאן ואינה נשענת על כך שהזיהוי-האוטומטי ממילא ייכשל — זיהוי-שנכשל
        -- וכיבוי-מכוון נראים זהים על המסך ושונים לגמרי בקוד.
        'filter_key', false))$o2$) then
    raise exception 'm11 text report_m20_satisfaction #2: not exactly once'; end if;
  v_def := replace(v_def, $o2$'filter_key', false),
      jsonb_build_object(
        'type', 'bar',
        'title', 'מה מכעיס · ' || v_lri || to_char(v_with_neg, 'FM999,999,999') || v_pdi || ' משובים סימנו סיבה שלילית',
        -- 🪤 I1 · התאום של ההערה בגרף החיובי — אותה אזהרה, מהצד השני.
        'note', 'הסולם כאן עצמאי ואינו משותף לגרף החיובי שלצידו — אורך עמודה בגרף '
                'אחד אינו מייצג את אותו מספר בגרף השני.',
        -- 🪤 I1 · `series[].format` הוא הקודם ל-`unit` בגזירת תו-הסימון
        --    ובטולטיפ, והוא היה `null`. הערכים עצמם אינם זזים.
        'series', jsonb_build_array(jsonb_build_object('key', 'n', 'label', 'משובים', 'format', 'int')),
        'data', v_neg, 'xKey', 'reason', 'domain', null, 'refLines', '[]'::jsonb,
      -- 🪤 I1 · **`chart.unit` הוא שם-פורמט של C8, לא מחרוזת-תצוגה.**
      --    ‏`ChartCard.valueFormat` מחזיר `series[0].format ?? unit` ומזין את
      --    ‏`formatAxisTick`, ו-`HebrewTooltip` מזין את `formatByType` — שניהם מצפים
      --    ל-`money|percent|int|ratio|score|days|text|date`. מחרוזת-תצוגה היא **פורמט
      --    לא-מוכר** ⇒ הציר נופל לקיבוץ-אלפים חשוף והטולטיפ ל-`text`.
      --    הכיתוב העברי נשמר ב-`unit_label` (תוספתי; **אין לו קורא היום** — מדווח).
        'unit', 'int', 'unit_label', 'משובים',
        -- 🪤 I1 · המוקאפ המאושר (`05_tab_customers_approved.html`) מצייר את שני גרפי-הסיבות
        --    **אופקית** — `aria-label` אומר *"עמודות אופקיות"* ותוויות-הקטגוריה עומדות
        --    ב-`x=129 text-anchor="end"`. שמות-הסיבות הם ביטויים עבריים בני 2–3 מילים, ובציר-X
        --    אנכי הם נחתכים. ‏`layout` הוא מפתח **תוספתי** שהמעטפת קוראת (`ChartCard.BarBody`).
        'layout', 'horizontal',
        -- ✅ **הסינון-הצולב היחיד שהמפגש שלו מדויק.** אוכלוסיית הגרף היא בדיוק
        -- אוכלוסיית הטבלה: כל שורה בטבלה סימנה סיבה שלילית אחת, וסכום העמודות
        -- (3+3+3+0+10) שווה ל-19 שורות הטבלה. **המספר שעל העמודה הוא מספר השורות**
        -- שהלחיצה תציג — וזה התנאי שמפריד בין סינון-צולב אמיתי לבין טבלה ריקה.
        -- `filter_key` הוא שם **שדה-השורה** ולא שם ה-`xKey`, והמעטפת משווה
        -- `row['negative_reason']` מול `datum['reason']` (`ReportSurface` §מפתח-הסינון ②).
        'filter_key', 'negative_reason'),
      jsonb_build_object(
        'type', 'bar',
        'title', 'שיעור המרוצים לפי שנה — אינו מושפע ממסנן התקופה',
        -- 🪤 I1 · **זה הגרף שהמדידה נקבה בו:** ציר-הערך קרא 0/25/50/75/100
        --    בלי `%`, כי `'%'` אינו שם-פורמט ו-`series[].format` היה `null`.
        'series', jsonb_build_array(jsonb_build_object('key', 'satisfied_share', 'label', 'שיעור מרוצים',
                                                      'format', 'percent')),
        'data', v_years, 'xKey', 'year',
        'domain', jsonb_build_array(0, 100), 'refLines', '[]'::jsonb, 'unit', 'percent',
        -- 🚫 **כבוי במפורש לפי הכרטיס עצמו** ① (*"לא לחיצה — הגרף מתעלם
        -- ממסנן-התקופה בכוונה, ולחיצה עליו הייתה סותרת את ההצהרה שלו"*). ההצהרה
        -- כתובה כאן ואינה נשענת על כך שהזיהוי-האוטומטי ממילא ייכשל — זיהוי-שנכשל
        -- וכיבוי-מכוון נראים זהים על המסך ושונים לגמרי בקוד.
        'filter_key', false))$o2$, $n2$'filter_key', false))$n2$);
  if (length(v_def) - length(replace(v_def, $o3$'note', 'הסולם כאן עצמאי ואינו משותף לגרף השלילי שלצידו — אורך עמודה בגרף '
                'אחד אינו מייצג את אותו מספר בגרף השני.',$o3$, ''))) <> length($o3$'note', 'הסולם כאן עצמאי ואינו משותף לגרף השלילי שלצידו — אורך עמודה בגרף '
                'אחד אינו מייצג את אותו מספר בגרף השני.',$o3$) then
    raise exception 'm11 text report_m20_satisfaction #3: not exactly once'; end if;
  v_def := replace(v_def, $o3$'note', 'הסולם כאן עצמאי ואינו משותף לגרף השלילי שלצידו — אורך עמודה בגרף '
                'אחד אינו מייצג את אותו מספר בגרף השני.',$o3$, $n3$$n3$);
  if (length(v_def) - length(replace(v_def, $o4$|| to_jsonb('גרף המגמה השנתית מתעלם ממסנן התקופה במכוון ומציג את כל השנים.'::text)
    -- 🪤 J1 · **שני דברים שאסור להם להיות על המסך היו כאן במשפט אחד:** '(📐11)' הוא
    --    קוד-כלל (כ4 שולח אותו להערת-HTML, וזו הדליפה היחידה מסוגה בכל 16 המשטחים),
    --    ו-'N מתוך M' מבקש מעובדת-שבוע-ראשון לקרוא שתי אותיות לטיניות כמספרים.
    --    המוסכמה נאמרת עכשיו במילים. את הסייג של רב-הסיבות נושאת ההערה שמעל
    --    (`v_max_tags`), ולכן המשפט הזה אינו חוזר עליו (R27).
    || to_jsonb('הספירות מוצגות כ"כמה מתוך כמה" ולא באחוזים.'::text)$o4$, ''))) <> length($o4$|| to_jsonb('גרף המגמה השנתית מתעלם ממסנן התקופה במכוון ומציג את כל השנים.'::text)
    -- 🪤 J1 · **שני דברים שאסור להם להיות על המסך היו כאן במשפט אחד:** '(📐11)' הוא
    --    קוד-כלל (כ4 שולח אותו להערת-HTML, וזו הדליפה היחידה מסוגה בכל 16 המשטחים),
    --    ו-'N מתוך M' מבקש מעובדת-שבוע-ראשון לקרוא שתי אותיות לטיניות כמספרים.
    --    המוסכמה נאמרת עכשיו במילים. את הסייג של רב-הסיבות נושאת ההערה שמעל
    --    (`v_max_tags`), ולכן המשפט הזה אינו חוזר עליו (R27).
    || to_jsonb('הספירות מוצגות כ"כמה מתוך כמה" ולא באחוזים.'::text)$o4$) then
    raise exception 'm11 text report_m20_satisfaction #4: not exactly once'; end if;
  v_def := replace(v_def, $o4$|| to_jsonb('גרף המגמה השנתית מתעלם ממסנן התקופה במכוון ומציג את כל השנים.'::text)
    -- 🪤 J1 · **שני דברים שאסור להם להיות על המסך היו כאן במשפט אחד:** '(📐11)' הוא
    --    קוד-כלל (כ4 שולח אותו להערת-HTML, וזו הדליפה היחידה מסוגה בכל 16 המשטחים),
    --    ו-'N מתוך M' מבקש מעובדת-שבוע-ראשון לקרוא שתי אותיות לטיניות כמספרים.
    --    המוסכמה נאמרת עכשיו במילים. את הסייג של רב-הסיבות נושאת ההערה שמעל
    --    (`v_max_tags`), ולכן המשפט הזה אינו חוזר עליו (R27).
    || to_jsonb('הספירות מוצגות כ"כמה מתוך כמה" ולא באחוזים.'::text)$o4$, $n4$$n4$);
  if (length(v_def) - length(replace(v_def, $o5$'הדף אינו דוח-קידוח (📐13) — פרמטר הקידוח לא הופעל.'$o5$, ''))) <> length($o5$'הדף אינו דוח-קידוח (📐13) — פרמטר הקידוח לא הופעל.'$o5$) then
    raise exception 'm11 text report_m20_satisfaction #5: not exactly once'; end if;
  v_def := replace(v_def, $o5$'הדף אינו דוח-קידוח (📐13) — פרמטר הקידוח לא הופעל.'$o5$, $n5$'הדוח הזה אינו תומך בקידוח.'$n5$);
  execute v_def;
end $m11$;

-- ═══ report_m21_drifting — 5 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m21_drifting';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'label', 'אוכלוסייה: ' || v_lri || to_char(v_elig, 'FM999,999,999') || v_pdi || ' לקוחות שקיימו '$o0$, ''))) <> length($o0$'label', 'אוכלוסייה: ' || v_lri || to_char(v_elig, 'FM999,999,999') || v_pdi || ' לקוחות שקיימו '$o0$) then
    raise exception 'm11 text report_m21_drifting #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'label', 'אוכלוסייה: ' || v_lri || to_char(v_elig, 'FM999,999,999') || v_pdi || ' לקוחות שקיימו '$o0$, $n0$'summary', v_lri || to_char(v_elig, 'FM999,999,999') || v_pdi || ' לקוחות עם 3+ אירועים · מתוך ' || v_lri || to_char((v_counts ->> 'customers')::integer, 'FM999,999,999') || v_pdi,
      'label', 'אוכלוסייה: ' || v_lri || to_char(v_elig, 'FM999,999,999') || v_pdi || ' לקוחות שקיימו '$n0$);
  if (length(v_def) - length(replace(v_def, $o1$|| ' ופי ' || v_lri || (v_call #>> '{1,ratio}') || v_pdi || ' מהקצב שלהן, יחד '
           || v_lri || to_char(round((v_call #>> '{0,revenue_12m}')::numeric
                                     + (v_call #>> '{1,revenue_12m}')::numeric), 'FM999,999,999') || ' ₪' || v_pdi
           || ' בשנה האחרונה, ושתיהן עדיין לא נחשבות "רדומות".' end,$o1$, ''))) <> length($o1$|| ' ופי ' || v_lri || (v_call #>> '{1,ratio}') || v_pdi || ' מהקצב שלהן, יחד '
           || v_lri || to_char(round((v_call #>> '{0,revenue_12m}')::numeric
                                     + (v_call #>> '{1,revenue_12m}')::numeric), 'FM999,999,999') || ' ₪' || v_pdi
           || ' בשנה האחרונה, ושתיהן עדיין לא נחשבות "רדומות".' end,$o1$) then
    raise exception 'm11 text report_m21_drifting #1: not exactly once'; end if;
  v_def := replace(v_def, $o1$|| ' ופי ' || v_lri || (v_call #>> '{1,ratio}') || v_pdi || ' מהקצב שלהן, יחד '
           || v_lri || to_char(round((v_call #>> '{0,revenue_12m}')::numeric
                                     + (v_call #>> '{1,revenue_12m}')::numeric), 'FM999,999,999') || ' ₪' || v_pdi
           || ' בשנה האחרונה, ושתיהן עדיין לא נחשבות "רדומות".' end,$o1$, $n1$|| ' ופי ' || v_lri || (v_call #>> '{1,ratio}') || v_pdi || ' מהקצב שלהן.' end,$n1$);
  if (length(v_def) - length(replace(v_def, $o2$ || ' · אינו מושפע ממסנן התקופה'$o2$, ''))) <> length($o2$ || ' · אינו מושפע ממסנן התקופה'$o2$) then
    raise exception 'm11 text report_m21_drifting #2: not exactly once'; end if;
  v_def := replace(v_def, $o2$ || ' · אינו מושפע ממסנן התקופה'$o2$, $n2$$n2$);
  if (length(v_def) - length(replace(v_def, $o3$|| to_jsonb('האריחים וההיסטוגרמה נמדדים על כלל הלקוחות ואינם מושפעים ממסנני התקופה והלקוח; הטבלה כן.'::text)$o3$, ''))) <> length($o3$|| to_jsonb('האריחים וההיסטוגרמה נמדדים על כלל הלקוחות ואינם מושפעים ממסנני התקופה והלקוח; הטבלה כן.'::text)$o3$) then
    raise exception 'm11 text report_m21_drifting #3: not exactly once'; end if;
  v_def := replace(v_def, $o3$|| to_jsonb('האריחים וההיסטוגרמה נמדדים על כלל הלקוחות ואינם מושפעים ממסנני התקופה והלקוח; הטבלה כן.'::text)$o3$, $n3$$n3$);
  if (length(v_def) - length(replace(v_def, $o4$'הדף אינו דוח-קידוח (📐13) — פרמטר הקידוח לא הופעל.'$o4$, ''))) <> length($o4$'הדף אינו דוח-קידוח (📐13) — פרמטר הקידוח לא הופעל.'$o4$) then
    raise exception 'm11 text report_m21_drifting #4: not exactly once'; end if;
  v_def := replace(v_def, $o4$'הדף אינו דוח-קידוח (📐13) — פרמטר הקידוח לא הופעל.'$o4$, $n4$'הדוח הזה אינו תומך בקידוח.'$n4$);
  execute v_def;
end $m11$;

-- ═══ report_m22_notes — 7 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m22_notes';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'label', 'אוכלוסייה: הערות חופשיות שלקוחות כתבו בטופס המשוב · '$o0$, ''))) <> length($o0$'label', 'אוכלוסייה: הערות חופשיות שלקוחות כתבו בטופס המשוב · '$o0$) then
    raise exception 'm11 text report_m22_notes #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'label', 'אוכלוסייה: הערות חופשיות שלקוחות כתבו בטופס המשוב · '$o0$, $n0$'summary', v_lri || to_char(v_with_note, 'FM999,999,999') || v_pdi || ' הערות · מתוך ' || v_lri || to_char(v_completed, 'FM999,999,999') || v_pdi || ' משובים',
      'label', 'אוכלוסייה: הערות חופשיות שלקוחות כתבו בטופס המשוב · '$n0$);
  if (length(v_def) - length(replace(v_def, $o1$ הדף אינו מגיב למסנן התקופה — הוא מציג את תוצאת כל ריצות-הניתוח שאושרו.'$o1$, ''))) <> length($o1$ הדף אינו מגיב למסנן התקופה — הוא מציג את תוצאת כל ריצות-הניתוח שאושרו.'$o1$) then
    raise exception 'm11 text report_m22_notes #1: not exactly once'; end if;
  v_def := replace(v_def, $o1$ הדף אינו מגיב למסנן התקופה — הוא מציג את תוצאת כל ריצות-הניתוח שאושרו.'$o1$, $n1$'$n1$);
  if (length(v_def) - length(replace(v_def, $o2$jsonb_build_object(
        'key', 'other_vs_categories',
        'label', 'גודל "אחר" מול הקטגוריות',
        'value', v_other,
        'format', 'int',
        -- 🪤 I2 · ה-`sub` הדפיס את אותו מספר שחצי-ההשוואה נושא כערך.
        'sub', '"אחר" מול ארבע הקטגוריות הקיימות יחד',
        'detail', jsonb_build_object('other', v_other, 'categories', v_rest, 'negative_total', v_other + v_rest),
        'window', 'כל הזמנים · נכון ל-' || v_lri || to_char(v_today, 'DD/MM') || v_pdi,
        'compare', jsonb_build_object(
          'value', v_rest,
          'label', 'מתוך ' || v_lri || to_char((v_other + v_rest), 'FM999,999,999') || v_pdi || ' המשובים השליליים בסך הכול',
          'direction', case when v_other > v_rest then 'up' when v_other < v_rest then 'down' else 'flat' end),
        'target', null),$o2$, ''))) <> length($o2$jsonb_build_object(
        'key', 'other_vs_categories',
        'label', 'גודל "אחר" מול הקטגוריות',
        'value', v_other,
        'format', 'int',
        -- 🪤 I2 · ה-`sub` הדפיס את אותו מספר שחצי-ההשוואה נושא כערך.
        'sub', '"אחר" מול ארבע הקטגוריות הקיימות יחד',
        'detail', jsonb_build_object('other', v_other, 'categories', v_rest, 'negative_total', v_other + v_rest),
        'window', 'כל הזמנים · נכון ל-' || v_lri || to_char(v_today, 'DD/MM') || v_pdi,
        'compare', jsonb_build_object(
          'value', v_rest,
          'label', 'מתוך ' || v_lri || to_char((v_other + v_rest), 'FM999,999,999') || v_pdi || ' המשובים השליליים בסך הכול',
          'direction', case when v_other > v_rest then 'up' when v_other < v_rest then 'down' else 'flat' end),
        'target', null),$o2$) then
    raise exception 'm11 text report_m22_notes #2: not exactly once'; end if;
  v_def := replace(v_def, $o2$jsonb_build_object(
        'key', 'other_vs_categories',
        'label', 'גודל "אחר" מול הקטגוריות',
        'value', v_other,
        'format', 'int',
        -- 🪤 I2 · ה-`sub` הדפיס את אותו מספר שחצי-ההשוואה נושא כערך.
        'sub', '"אחר" מול ארבע הקטגוריות הקיימות יחד',
        'detail', jsonb_build_object('other', v_other, 'categories', v_rest, 'negative_total', v_other + v_rest),
        'window', 'כל הזמנים · נכון ל-' || v_lri || to_char(v_today, 'DD/MM') || v_pdi,
        'compare', jsonb_build_object(
          'value', v_rest,
          'label', 'מתוך ' || v_lri || to_char((v_other + v_rest), 'FM999,999,999') || v_pdi || ' המשובים השליליים בסך הכול',
          'direction', case when v_other > v_rest then 'up' when v_other < v_rest then 'down' else 'flat' end),
        'target', null),$o2$, $n2$$n2$);
  if (length(v_def) - length(replace(v_def, $o3$'free_notes', 'other_tagged_notes', 'other_vs_categories'),$o3$, ''))) <> length($o3$'free_notes', 'other_tagged_notes', 'other_vs_categories'),$o3$) then
    raise exception 'm11 text report_m22_notes #3: not exactly once'; end if;
  v_def := replace(v_def, $o3$'free_notes', 'other_tagged_notes', 'other_vs_categories'),$o3$, $n3$'free_notes', 'other_tagged_notes'),$n3$);
  if (length(v_def) - length(replace(v_def, $o4$|| to_jsonb('הדף אינו מגיב למסנן התקופה — הוא מציג את תוצאת כל ריצות-הניתוח שאושרו.'::text)
    -- 🔴 **ההצהרה הקודמת הייתה שקרית על אריח אחד מארבעה.** *"אריחי המצאי … אינם
    -- מושפעים ממסנן הלקוח"* נכון לשלושת אריחי-המצאי, **ולא ל"דגלים אדומים"** — שהוא
    -- כן מסונן (נמדד: 24 ⇐ 5 עם `p_customer_id=401`). המשפט נוקב עכשיו בשלושה,
    -- ו-`meta.customer_filter_ignored` מונה אותם במפורש.
    || to_jsonb('שלושת אריחי המצאי — הערות, "אחר", ו"אחר" מול הקטגוריות — נספרים על כל הזמנים ואינם מושפעים ממסנן הלקוח; אריח הדגלים האדומים והטבלה כן מושפעים ממנו.'::text)$o4$, ''))) <> length($o4$|| to_jsonb('הדף אינו מגיב למסנן התקופה — הוא מציג את תוצאת כל ריצות-הניתוח שאושרו.'::text)
    -- 🔴 **ההצהרה הקודמת הייתה שקרית על אריח אחד מארבעה.** *"אריחי המצאי … אינם
    -- מושפעים ממסנן הלקוח"* נכון לשלושת אריחי-המצאי, **ולא ל"דגלים אדומים"** — שהוא
    -- כן מסונן (נמדד: 24 ⇐ 5 עם `p_customer_id=401`). המשפט נוקב עכשיו בשלושה,
    -- ו-`meta.customer_filter_ignored` מונה אותם במפורש.
    || to_jsonb('שלושת אריחי המצאי — הערות, "אחר", ו"אחר" מול הקטגוריות — נספרים על כל הזמנים ואינם מושפעים ממסנן הלקוח; אריח הדגלים האדומים והטבלה כן מושפעים ממנו.'::text)$o4$) then
    raise exception 'm11 text report_m22_notes #4: not exactly once'; end if;
  v_def := replace(v_def, $o4$|| to_jsonb('הדף אינו מגיב למסנן התקופה — הוא מציג את תוצאת כל ריצות-הניתוח שאושרו.'::text)
    -- 🔴 **ההצהרה הקודמת הייתה שקרית על אריח אחד מארבעה.** *"אריחי המצאי … אינם
    -- מושפעים ממסנן הלקוח"* נכון לשלושת אריחי-המצאי, **ולא ל"דגלים אדומים"** — שהוא
    -- כן מסונן (נמדד: 24 ⇐ 5 עם `p_customer_id=401`). המשפט נוקב עכשיו בשלושה,
    -- ו-`meta.customer_filter_ignored` מונה אותם במפורש.
    || to_jsonb('שלושת אריחי המצאי — הערות, "אחר", ו"אחר" מול הקטגוריות — נספרים על כל הזמנים ואינם מושפעים ממסנן הלקוח; אריח הדגלים האדומים והטבלה כן מושפעים ממנו.'::text)$o4$, $n4$$n4$);
  if (length(v_def) - length(replace(v_def, $o5$'אין תקופה קודמת להשוואה — זהו המצאי המצטבר, לא מדד תקופתי'$o5$, ''))) <> length($o5$'אין תקופה קודמת להשוואה — זהו המצאי המצטבר, לא מדד תקופתי'$o5$) then
    raise exception 'm11 text report_m22_notes #5: not exactly once'; end if;
  v_def := replace(v_def, $o5$'אין תקופה קודמת להשוואה — זהו המצאי המצטבר, לא מדד תקופתי'$o5$, $n5$'אין תקופה קודמת להשוואה'$n5$);
  if (length(v_def) - length(replace(v_def, $o6$'הדף אינו דוח-קידוח (📐13) — פרמטר הקידוח לא הופעל.'$o6$, ''))) <> length($o6$'הדף אינו דוח-קידוח (📐13) — פרמטר הקידוח לא הופעל.'$o6$) then
    raise exception 'm11 text report_m22_notes #6: not exactly once'; end if;
  v_def := replace(v_def, $o6$'הדף אינו דוח-קידוח (📐13) — פרמטר הקידוח לא הופעל.'$o6$, $n6$'הדוח הזה אינו תומך בקידוח.'$n6$);
  execute v_def;
end $m11$;
