-- why: מ11 פזה ב׳ — סבב-טקסט רביעי (L4), 23/09/2026. מיד אחרי L3, קריאה למ08 על 2025 החזירה
--      "הרווח סופי ב-286 מתוך 286 הפרויקטים; בשאר הוא מחושב…" — אין "שאר" כשכל הפרויקטים סופיים
--      (אותו פגם היה גם בנוסח שלפני L3). עכשיו ההערה נבחרת לפי המקרה: כולם סופיים · אף אחד · חלק.
--      ישי 23/09: "מעכשיו בסשן הזה תכיל לבד" — הוחל בהרשאה הזו, עם הסבר בעברית בצ'אט.
-- what: פונקציה אחת (report_m08_profitability), החלפה אחת — הערת-השוליים של הרווח הסופי.
-- how: אותה טכניקה כמו L1–L3 — pg_get_functiondef + replace מדויק, "בדיוק פעם אחת" (אחרת raise), execute.
--      אותה חתימה ⇒ הרשאות והערות נשמרות. אין שינוי-סכמה ואין שינוי בנתונים.
-- verified before apply (23/09/2026): הגוף שממנו נבנתה ההחלפה = הגוף החי אחרי L3 (md5 == expect-md5 l3).
-- reversible: כן — ההחלפה ההפוכה מחזירה; המצב הקודם שמור ב-L3.
-- generated by: docs/specs/module_11_reports/phase-b-migration/gen-migration.mjs --ops ops-l4.mjs (לא נערך ידנית).
-- ═══ report_m08_profitability — 1 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m08_profitability';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'הרווח סופי ב-' || v_lri || v_frozen || v_pdi || ' מתוך ' || v_lri || v_n || v_pdi
          || ' הפרויקטים; בשאר הוא מחושב מהעלויות שנרשמו עד היום.'),$o0$, ''))) <> length($o0$'הרווח סופי ב-' || v_lri || v_frozen || v_pdi || ' מתוך ' || v_lri || v_n || v_pdi
          || ' הפרויקטים; בשאר הוא מחושב מהעלויות שנרשמו עד היום.'),$o0$) then
    raise exception 'm11 text report_m08_profitability #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'הרווח סופי ב-' || v_lri || v_frozen || v_pdi || ' מתוך ' || v_lri || v_n || v_pdi
          || ' הפרויקטים; בשאר הוא מחושב מהעלויות שנרשמו עד היום.'),$o0$, $n0$case when v_frozen >= v_n then 'הרווח סופי בכל ' || v_lri || v_n || v_pdi || ' הפרויקטים.'
               when coalesce(v_frozen, 0) = 0 then 'הרווח בכל ' || v_lri || v_n || v_pdi || ' הפרויקטים מחושב מהעלויות שנרשמו עד היום.'
               else 'הרווח סופי ב-' || v_lri || v_frozen || v_pdi || ' מתוך ' || v_lri || v_n || v_pdi
                    || ' הפרויקטים; בשאר הוא מחושב מהעלויות שנרשמו עד היום.' end),$n0$);
  execute v_def;
end $m11$;
