-- why: מ11 — תקן-הכרטיס, סבב שני (L6), 23/09/2026 לילה. הרצה חוזרת של בדיקת-הצפיפות אחרי L5 מצאה ארבע
--      שורות-כרטיס שנשברות לשתי שורות על המסך, אפס בלי בסיס גלוי (מ07), הערת-שוליים שעדיין עוברת את
--      תקציב-הדף (מ08), והשוואה שהחלפת-הערך של L5 גרמה לה להיקרא כ"ימים" (מ21 — ציון-משוב, לא ימים).
--      ישי 23/09 לילה: "לא לבקש אישור להכיל מיגרציות בסשן הזה. תכיל בעצמך ותאמת לבד".
-- what: 4 פונקציות (m07 · m08 · m17 · m21), 6 החלפות-טקסט. אף מספר, אוכלוסייה או עמודה אינם משתנים.
-- how: אותה טכניקה כמו L1–L5 — pg_get_functiondef + replace מדויק, "בדיוק פעם אחת" (אחרת raise), execute.
--      אותה חתימה ⇒ הרשאות והערות נשמרות. אין שינוי-סכמה ואין שינוי בנתונים.
-- verified before apply: הגוף שממנו נבנו ההחלפות = הגוף החי אחרי L5 (md5 9/9 == expect-md5 l5, נמדד אחרי ההחלה).
-- reversible: כן — ההחלפות ההפוכות מחזירות; המצב הקודם שמור ב-L5.
-- generated by: docs/specs/module_11_reports/phase-b-migration/gen-migration.mjs --ops ops-l6.mjs (לא נערך ידנית).

-- ═══ report_m07_finance_overview — 2 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m07_finance_overview';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'label', 'נכנסו ב-30 הימים שחלפו',$o0$, ''))) <> length($o0$'label', 'נכנסו ב-30 הימים שחלפו',$o0$) then
    raise exception 'm11 text report_m07_finance_overview #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'label', 'נכנסו ב-30 הימים שחלפו',$o0$, $n0$'label', 'נכנסו בפועל',$n0$);
  if (length(v_def) - length(replace(v_def, $o1$else 'מתוך ' || v_lri || v_dev_den || v_pdi || ' אירועים שהתקיימו ב'
                         || v_months_he[extract(month from v_to)::integer]
                         || case when v_dev_n = 0 then ' — אף אחד לא חרג' else '' end end,$o1$, ''))) <> length($o1$else 'מתוך ' || v_lri || v_dev_den || v_pdi || ' אירועים שהתקיימו ב'
                         || v_months_he[extract(month from v_to)::integer]
                         || case when v_dev_n = 0 then ' — אף אחד לא חרג' else '' end end,$o1$) then
    raise exception 'm11 text report_m07_finance_overview #1: not exactly once'; end if;
  v_def := replace(v_def, $o1$else 'מתוך ' || v_lri || v_dev_den || v_pdi || ' אירועים שהתקיימו ב'
                         || v_months_he[extract(month from v_to)::integer]
                         || case when v_dev_n = 0 then ' — אף אחד לא חרג' else '' end end,$o1$, $n1$else 'מתוך ' || v_lri || v_dev_den || v_pdi || ' אירועים' end,$n1$);
  execute v_def;
end $m11$;

-- ═══ report_m08_profitability — 1 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m08_profitability';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$' פרויקטים קטנים (מתחת ל-' || v_lri || '4' || v_pdi || ' שעות או '
          || v_lri || '1,000' || ' ₪' || v_pdi || ') אינם בדירוג החריגות.',$o0$, ''))) <> length($o0$' פרויקטים קטנים (מתחת ל-' || v_lri || '4' || v_pdi || ' שעות או '
          || v_lri || '1,000' || ' ₪' || v_pdi || ') אינם בדירוג החריגות.',$o0$) then
    raise exception 'm11 text report_m08_profitability #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$' פרויקטים קטנים (מתחת ל-' || v_lri || '4' || v_pdi || ' שעות או '
          || v_lri || '1,000' || ' ₪' || v_pdi || ') אינם בדירוג החריגות.',$o0$, $n0$' פרויקטים מתחת ל-' || v_lri || '4' || v_pdi || ' שעות או '
          || v_lri || '1,000' || ' ₪' || v_pdi || ' אינם מדורגים.',$n0$);
  execute v_def;
end $m11$;

-- ═══ report_m17_fairness — 2 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m17_fairness';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'sub', v_lri || to_char(coalesce(v_answered, 0), 'FM999,999') || v_pdi || ' ענו מתוך ' ||
               v_lri || to_char(coalesce(v_invites, 0), 'FM999,999') || v_pdi || ' שזומנו',$o0$, ''))) <> length($o0$'sub', v_lri || to_char(coalesce(v_answered, 0), 'FM999,999') || v_pdi || ' ענו מתוך ' ||
               v_lri || to_char(coalesce(v_invites, 0), 'FM999,999') || v_pdi || ' שזומנו',$o0$) then
    raise exception 'm11 text report_m17_fairness #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'sub', v_lri || to_char(coalesce(v_answered, 0), 'FM999,999') || v_pdi || ' ענו מתוך ' ||
               v_lri || to_char(coalesce(v_invites, 0), 'FM999,999') || v_pdi || ' שזומנו',$o0$, $n0$'sub', v_lri || to_char(coalesce(v_answered, 0), 'FM999,999') || v_pdi || ' מתוך ' ||
               v_lri || to_char(coalesce(v_invites, 0), 'FM999,999') || v_pdi,$n0$);
  if (length(v_def) - length(replace(v_def, $o1$'note', 'הקו הישר הוא חלוקה שווה; ככל שהעקומה רחוקה ממנו — ריכוזי יותר.',$o1$, ''))) <> length($o1$'note', 'הקו הישר הוא חלוקה שווה; ככל שהעקומה רחוקה ממנו — ריכוזי יותר.',$o1$) then
    raise exception 'm11 text report_m17_fairness #1: not exactly once'; end if;
  v_def := replace(v_def, $o1$'note', 'הקו הישר הוא חלוקה שווה; ככל שהעקומה רחוקה ממנו — ריכוזי יותר.',$o1$, $n1$'note', 'הקו הישר הוא חלוקה שווה; עקומה רחוקה ממנו — חלוקה ריכוזית.',$n1$);
  execute v_def;
end $m11$;

-- ═══ report_m21_drifting — 1 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m21_drifting';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'label', 'ממוצע המשוב שלו על ' || v_lri || to_char((v_oldest ->> 'feedback_n')::integer, 'FM999,999,999') || v_pdi || ' משובים'
                     || case when (v_oldest ->> 'lowest_avg')::boolean then ' — הנמוך ברשימה' else '' end,$o0$, ''))) <> length($o0$'label', 'ממוצע המשוב שלו על ' || v_lri || to_char((v_oldest ->> 'feedback_n')::integer, 'FM999,999,999') || v_pdi || ' משובים'
                     || case when (v_oldest ->> 'lowest_avg')::boolean then ' — הנמוך ברשימה' else '' end,$o0$) then
    raise exception 'm11 text report_m21_drifting #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'label', 'ממוצע המשוב שלו על ' || v_lri || to_char((v_oldest ->> 'feedback_n')::integer, 'FM999,999,999') || v_pdi || ' משובים'
                     || case when (v_oldest ->> 'lowest_avg')::boolean then ' — הנמוך ברשימה' else '' end,$o0$, $n0$'label', 'ממוצע המשוב', 'format', 'text',$n0$);
  execute v_def;
end $m11$;
