-- why: מ11 — תקן-הכרטיס, החצי השני (L5), 23/09/2026 לילה. הרכיב כבר מציג כרטיס = שם · מספר · השוואה ·
--      שורת-הקשר קצרה אחת, והשאר ב-ⓘ (baf43c0e + ea38925f). מה שהרכיב לא יכול לתקן הוא הטקסט שמגיע מהשרת:
--      כותרות-כרטיס שהן טענות ("הריכוזיות והנטישה עוד לא נפגשות" מעל 0), ערך-גיבור שהוא שם-לקוח,
--      השוואה שהיא משפט-פירוק ("פילוח לפי שנה … 2024: 4 · 2025: 19"), תאריך בתוך כרטיס, והערות-שוליים
--      שעוברות את תקציב-המלל של הדף. כל החלפה כאן עונה על חריגה שבדיקת-הצפיפות מצאה
--      (e2e/report-density.spec.js · docs/plans/2026-09-23-module-11-decision-reports.md §4ה).
--      ישי 23/09 לילה: "לא לבקש אישור להכיל מיגרציות בסשן הזה. תכיל בעצמך ותאמת לבד".
-- what: 9 פונקציות (m07 · m08 · m09 · m12 · m16 · m17 · m19 · m21 · m22), 29 החלפות-טקסט. אף מספר, אוכלוסייה
--      או עמודה אינם משתנים. חריג אחד שאינו טקסט בלבד: אריח "הוותיק ברשימה" במ21 מציג עכשיו את מספר
--      הימים כערך (ולא את שם-הלקוח), והשם עובר לשורת-ההקשר — אותו נתון, בצורה שהכרטיס מחייב.
-- how: אותה טכניקה כמו L1–L4 — pg_get_functiondef + replace מדויק, "בדיוק פעם אחת" (אחרת raise), execute.
--      אותה חתימה ⇒ הרשאות והערות נשמרות. אין שינוי-סכמה ואין שינוי בנתונים.
-- verified before apply (23/09/2026): הגוף שממנו נבנו ההחלפות = הגוף החי אחרי L4 (md5 13/13 == postL4).
-- reversible: כן — ההחלפות ההפוכות מחזירות; המצב הקודם שמור ב-L4.
-- ⚠️ amends a 🔒 dictionary row: "הכנסת 12 החודשים של הלקוחות המסומנים" ⇒ "הכנסת הלקוחות המסומנים". הנעילה
--    אומרת "לא 'הכנסה-בסיכון'" — וזה נשמר; רק התקופה עוברת ל-ⓘ (כלל 0.8). נרשם ב-processes-approved.md.
-- generated by: docs/specs/module_11_reports/phase-b-migration/gen-migration.mjs --ops ops-l5.mjs (לא נערך ידנית).

-- ═══ report_m07_finance_overview — 2 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m07_finance_overview';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'חובות אבודים: ' || v_lri || v_written_n || v_pdi
          || case when v_written_n = 1 then ' חשבונית · ' else ' חשבוניות · ' end
          || v_lri || to_char(round(v_written_sum), 'FM999,999,999') || ' ₪' || v_pdi
          || ' — מוחרגים מהיתרה ומכל המדרגים.'$o0$, ''))) <> length($o0$'חובות אבודים: ' || v_lri || v_written_n || v_pdi
          || case when v_written_n = 1 then ' חשבונית · ' else ' חשבוניות · ' end
          || v_lri || to_char(round(v_written_sum), 'FM999,999,999') || ' ₪' || v_pdi
          || ' — מוחרגים מהיתרה ומכל המדרגים.'$o0$) then
    raise exception 'm11 text report_m07_finance_overview #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'חובות אבודים: ' || v_lri || v_written_n || v_pdi
          || case when v_written_n = 1 then ' חשבונית · ' else ' חשבוניות · ' end
          || v_lri || to_char(round(v_written_sum), 'FM999,999,999') || ' ₪' || v_pdi
          || ' — מוחרגים מהיתרה ומכל המדרגים.'$o0$, $n0$v_lri || v_written_n || v_pdi
          || case when v_written_n = 1 then ' חוב אבוד (' else ' חובות אבודים (' end
          || v_lri || to_char(round(v_written_sum), 'FM999,999,999') || ' ₪' || v_pdi
          || ') אינם ביתרה ובמדרגים.'$n0$);
  if (length(v_def) - length(replace(v_def, $o1$'label', 'שנכנסו בפועל ב-30 הימים האחרונים',$o1$, ''))) <> length($o1$'label', 'שנכנסו בפועל ב-30 הימים האחרונים',$o1$) then
    raise exception 'm11 text report_m07_finance_overview #1: not exactly once'; end if;
  v_def := replace(v_def, $o1$'label', 'שנכנסו בפועל ב-30 הימים האחרונים',$o1$, $n1$'label', 'נכנסו ב-30 הימים שחלפו',$n1$);
  execute v_def;
end $m11$;

-- ═══ report_m08_profitability — 2 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m08_profitability';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$' פרויקטים קטנים (פחות מ-' || v_lri || '4' || v_pdi || ' שעות או מ-'
          || v_lri || '1,000' || ' ₪' || v_pdi || ' עלות-עבודה) נספרים בסכומים, אבל לא בדירוג החריגות.',$o0$, ''))) <> length($o0$' פרויקטים קטנים (פחות מ-' || v_lri || '4' || v_pdi || ' שעות או מ-'
          || v_lri || '1,000' || ' ₪' || v_pdi || ' עלות-עבודה) נספרים בסכומים, אבל לא בדירוג החריגות.',$o0$) then
    raise exception 'm11 text report_m08_profitability #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$' פרויקטים קטנים (פחות מ-' || v_lri || '4' || v_pdi || ' שעות או מ-'
          || v_lri || '1,000' || ' ₪' || v_pdi || ' עלות-עבודה) נספרים בסכומים, אבל לא בדירוג החריגות.',$o0$, $n0$' פרויקטים קטנים (מתחת ל-' || v_lri || '4' || v_pdi || ' שעות או '
          || v_lri || '1,000' || ' ₪' || v_pdi || ') אינם בדירוג החריגות.',$n0$);
  if (length(v_def) - length(replace(v_def, $o1$' הפרויקטים; בשאר הוא מחושב מהעלויות שנרשמו עד היום.' end),$o1$, ''))) <> length($o1$' הפרויקטים; בשאר הוא מחושב מהעלויות שנרשמו עד היום.' end),$o1$) then
    raise exception 'm11 text report_m08_profitability #1: not exactly once'; end if;
  v_def := replace(v_def, $o1$' הפרויקטים; בשאר הוא מחושב מהעלויות שנרשמו עד היום.' end),$o1$, $n1$' פרויקטים; בשאר — לפי העלויות עד היום.' end),$n1$);
  execute v_def;
end $m11$;

-- ═══ report_m09_aging — 3 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m09_aging';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$v_chart_note := 'העמודות הן החוב שכבר איחר, לפי ותק; חוב שמועדו טרם הגיע מופיע באריח שלצד הגרף.';$o0$, ''))) <> length($o0$v_chart_note := 'העמודות הן החוב שכבר איחר, לפי ותק; חוב שמועדו טרם הגיע מופיע באריח שלצד הגרף.';$o0$) then
    raise exception 'm11 text report_m09_aging #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$v_chart_note := 'העמודות הן החוב שכבר איחר, לפי ותק; חוב שמועדו טרם הגיע מופיע באריח שלצד הגרף.';$o0$, $n0$v_chart_note := 'חוב שכבר איחר, לפי ותק. חוב שוטף — באריח שליד הגרף.';$n0$);
  if (length(v_def) - length(replace(v_def, $o1$'חובות אבודים: ' || v_lri || v_written_n || v_pdi
          || case when v_written_n = 1 then ' חשבונית · ' else ' חשבוניות · ' end
          || v_lri || to_char(round(v_written_sum), 'FM999,999,999') || ' ₪' || v_pdi
          || ' — מוחרגים מהיתרה ומכל המדרגים.'$o1$, ''))) <> length($o1$'חובות אבודים: ' || v_lri || v_written_n || v_pdi
          || case when v_written_n = 1 then ' חשבונית · ' else ' חשבוניות · ' end
          || v_lri || to_char(round(v_written_sum), 'FM999,999,999') || ' ₪' || v_pdi
          || ' — מוחרגים מהיתרה ומכל המדרגים.'$o1$) then
    raise exception 'm11 text report_m09_aging #1: not exactly once'; end if;
  v_def := replace(v_def, $o1$'חובות אבודים: ' || v_lri || v_written_n || v_pdi
          || case when v_written_n = 1 then ' חשבונית · ' else ' חשבוניות · ' end
          || v_lri || to_char(round(v_written_sum), 'FM999,999,999') || ' ₪' || v_pdi
          || ' — מוחרגים מהיתרה ומכל המדרגים.'$o1$, $n1$v_lri || v_written_n || v_pdi
          || case when v_written_n = 1 then ' חוב אבוד (' else ' חובות אבודים (' end
          || v_lri || to_char(round(v_written_sum), 'FM999,999,999') || ' ₪' || v_pdi
          || ') אינם ביתרה ובמדרגים.'$n1$);
  if (length(v_def) - length(replace(v_def, $o2$,
        'החשבונית הישנה ביותר: ' || v_lri || coalesce(v_oldest_days, 0) || v_pdi || ' ימי איחור · '
          || coalesce(v_oldest_name, '—') || ' · נשלחה '
          || v_lri || coalesce(to_char(v_oldest_sent, 'DD/MM/YYYY'), '—') || v_pdi || '.'),$o2$, ''))) <> length($o2$,
        'החשבונית הישנה ביותר: ' || v_lri || coalesce(v_oldest_days, 0) || v_pdi || ' ימי איחור · '
          || coalesce(v_oldest_name, '—') || ' · נשלחה '
          || v_lri || coalesce(to_char(v_oldest_sent, 'DD/MM/YYYY'), '—') || v_pdi || '.'),$o2$) then
    raise exception 'm11 text report_m09_aging #2: not exactly once'; end if;
  v_def := replace(v_def, $o2$,
        'החשבונית הישנה ביותר: ' || v_lri || coalesce(v_oldest_days, 0) || v_pdi || ' ימי איחור · '
          || coalesce(v_oldest_name, '—') || ' · נשלחה '
          || v_lri || coalesce(to_char(v_oldest_sent, 'DD/MM/YYYY'), '—') || v_pdi || '.'),$o2$, $n2$),$n2$);
  execute v_def;
end $m11$;

-- ═══ report_m12_equipment — 1 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m12_equipment';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'label', 'עלות ציוד — כל הזמנים',$o0$, ''))) <> length($o0$'label', 'עלות ציוד — כל הזמנים',$o0$) then
    raise exception 'm11 text report_m12_equipment #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'label', 'עלות ציוד — כל הזמנים',$o0$, $n0$'label', 'עלות ציוד מצטברת',$n0$);
  execute v_def;
end $m11$;

-- ═══ report_m16_quality_cost — 1 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m16_quality_cost';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$' דיילות ללא דירוג אינן בגרף — ראי את השבב ''בלי דירוג בלבד'' בטבלה.',$o0$, ''))) <> length($o0$' דיילות ללא דירוג אינן בגרף — ראי את השבב ''בלי דירוג בלבד'' בטבלה.',$o0$) then
    raise exception 'm11 text report_m16_quality_cost #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$' דיילות ללא דירוג אינן בגרף — ראי את השבב ''בלי דירוג בלבד'' בטבלה.',$o0$, $n0$' בלי דירוג אינן בגרף — הן בשבב ''בלי דירוג בלבד''.',$n0$);
  execute v_def;
end $m11$;

-- ═══ report_m17_fairness — 1 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m17_fairness';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'note', 'הקו הישר הוא חלוקה שווה; ככל שהעקומה רחוקה ממנו — החלוקה ריכוזית יותר.',$o0$, ''))) <> length($o0$'note', 'הקו הישר הוא חלוקה שווה; ככל שהעקומה רחוקה ממנו — החלוקה ריכוזית יותר.',$o0$) then
    raise exception 'm11 text report_m17_fairness #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'note', 'הקו הישר הוא חלוקה שווה; ככל שהעקומה רחוקה ממנו — החלוקה ריכוזית יותר.',$o0$, $n0$'note', 'הקו הישר הוא חלוקה שווה; ככל שהעקומה רחוקה ממנו — ריכוזי יותר.',$n0$);
  execute v_def;
end $m11$;

-- ═══ report_m19_customers_overview — 11 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m19_customers_overview';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'label', 'שביעות-רצון מנבאת חזרה',$o0$, ''))) <> length($o0$'label', 'שביעות-רצון מנבאת חזרה',$o0$) then
    raise exception 'm11 text report_m19_customers_overview #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'label', 'שביעות-רצון מנבאת חזרה',$o0$, $n0$'label', 'ימים מאז אירוע, מרוצים',$n0$);
  if (length(v_def) - length(replace(v_def, $o1$'sub', 'ימים מאז האירוע האחרון (חציון) — מרוצים מול לא-מרוצים',$o1$, ''))) <> length($o1$'sub', 'ימים מאז האירוע האחרון (חציון) — מרוצים מול לא-מרוצים',$o1$) then
    raise exception 'm11 text report_m19_customers_overview #1: not exactly once'; end if;
  v_def := replace(v_def, $o1$'sub', 'ימים מאז האירוע האחרון (חציון) — מרוצים מול לא-מרוצים',$o1$, $n1$'sub', 'חציון · ' || v_lri || to_char(v_in_buckets, 'FM999,999,999') || v_pdi || ' לקוחות',$n1$);
  if (length(v_def) - length(replace(v_def, $o2$'label', 'לקוחות לא-מרוצים',$o2$, ''))) <> length($o2$'label', 'לקוחות לא-מרוצים',$o2$) then
    raise exception 'm11 text report_m19_customers_overview #2: not exactly once'; end if;
  v_def := replace(v_def, $o2$'label', 'לקוחות לא-מרוצים',$o2$, $n2$'label', 'לא-מרוצים',$n2$);
  if (length(v_def) - length(replace(v_def, $o3$'label', 'הסיבה השלילית הגדולה אינה קטגוריה',$o3$, ''))) <> length($o3$'label', 'הסיבה השלילית הגדולה אינה קטגוריה',$o3$) then
    raise exception 'm11 text report_m19_customers_overview #3: not exactly once'; end if;
  v_def := replace(v_def, $o3$'label', 'הסיבה השלילית הגדולה אינה קטגוריה',$o3$, $n3$'label', 'משובים שליליים «אחר»',$n3$);
  if (length(v_def) - length(replace(v_def, $o4$'sub', 'תויגו "אחר" מתוך ' || v_lri || to_char(v_neg_total, 'FM999,999,999') || v_pdi
               || ' משובים שליליים',$o4$, ''))) <> length($o4$'sub', 'תויגו "אחר" מתוך ' || v_lri || to_char(v_neg_total, 'FM999,999,999') || v_pdi
               || ' משובים שליליים',$o4$) then
    raise exception 'm11 text report_m19_customers_overview #4: not exactly once'; end if;
  v_def := replace(v_def, $o4$'sub', 'תויגו "אחר" מתוך ' || v_lri || to_char(v_neg_total, 'FM999,999,999') || v_pdi
               || ' משובים שליליים',$o4$, $n4$'sub', 'מתוך ' || v_lri || to_char(v_neg_total, 'FM999,999,999') || v_pdi || ' שליליים',$n4$);
  if (length(v_def) - length(replace(v_def, $o5$'window', 'כל הזמנים · לכל ' || v_lri || to_char(v_other, 'FM999,999,999') || v_pdi
                  || ' יש הערה חופשית',
        'compare', jsonb_build_object(
          'value', coalesce(v_other_year_txt, '—'),
          'label', 'פילוח לפי שנה (השנה הנוכחית חלקית)', 'direction', 'flat'),$o5$, ''))) <> length($o5$'window', 'כל הזמנים · לכל ' || v_lri || to_char(v_other, 'FM999,999,999') || v_pdi
                  || ' יש הערה חופשית',
        'compare', jsonb_build_object(
          'value', coalesce(v_other_year_txt, '—'),
          'label', 'פילוח לפי שנה (השנה הנוכחית חלקית)', 'direction', 'flat'),$o5$) then
    raise exception 'm11 text report_m19_customers_overview #5: not exactly once'; end if;
  v_def := replace(v_def, $o5$'window', 'כל הזמנים · לכל ' || v_lri || to_char(v_other, 'FM999,999,999') || v_pdi
                  || ' יש הערה חופשית',
        'compare', jsonb_build_object(
          'value', coalesce(v_other_year_txt, '—'),
          'label', 'פילוח לפי שנה (השנה הנוכחית חלקית)', 'direction', 'flat'),$o5$, $n5$'window', 'כל הזמנים · לכל ' || v_lri || to_char(v_other, 'FM999,999,999') || v_pdi
                  || ' יש הערה חופשית · לפי שנה (השנה הנוכחית חלקית): ' || coalesce(v_other_year_txt, '—'),
        'compare', null,$n5$);
  if (length(v_def) - length(replace(v_def, $o6$'label', 'הריכוזיות והנטישה עוד לא נפגשות',$o6$, ''))) <> length($o6$'label', 'הריכוזיות והנטישה עוד לא נפגשות',$o6$) then
    raise exception 'm11 text report_m19_customers_overview #6: not exactly once'; end if;
  v_def := replace(v_def, $o6$'label', 'הריכוזיות והנטישה עוד לא נפגשות',$o6$, $n6$'label', 'גדולים שמתרחקים',$n6$);
  if (length(v_def) - length(replace(v_def, $o7$'sub', v_lri || to_char((v_conc ->> 'top5_drifting')::integer, 'FM999,999,999') || v_pdi
               || ' מחמשת הגדולים ('
               || v_lri || coalesce(to_char(round(100 * (v_conc ->> 'top5_revenue')::numeric
                          / nullif((v_conc ->> 'total_revenue')::numeric, 0), 1), 'FM999990.0'), '—')
               || '%' || v_pdi || ' מההכנסה) מסומנים "מתרחק"',$o7$, ''))) <> length($o7$'sub', v_lri || to_char((v_conc ->> 'top5_drifting')::integer, 'FM999,999,999') || v_pdi
               || ' מחמשת הגדולים ('
               || v_lri || coalesce(to_char(round(100 * (v_conc ->> 'top5_revenue')::numeric
                          / nullif((v_conc ->> 'total_revenue')::numeric, 0), 1), 'FM999990.0'), '—')
               || '%' || v_pdi || ' מההכנסה) מסומנים "מתרחק"',$o7$) then
    raise exception 'm11 text report_m19_customers_overview #7: not exactly once'; end if;
  v_def := replace(v_def, $o7$'sub', v_lri || to_char((v_conc ->> 'top5_drifting')::integer, 'FM999,999,999') || v_pdi
               || ' מחמשת הגדולים ('
               || v_lri || coalesce(to_char(round(100 * (v_conc ->> 'top5_revenue')::numeric
                          / nullif((v_conc ->> 'total_revenue')::numeric, 0), 1), 'FM999990.0'), '—')
               || '%' || v_pdi || ' מההכנסה) מסומנים "מתרחק"',$o7$, $n7$'sub', 'מתוך ' || v_lri || '5' || v_pdi || ' הלקוחות הגדולים',
        'share', v_lri || coalesce(to_char(round(100 * (v_conc ->> 'top5_revenue')::numeric
                          / nullif((v_conc ->> 'total_revenue')::numeric, 0), 1), 'FM999990.0'), '—')
               || '%' || v_pdi || ' מההכנסה',$n7$);
  if (length(v_def) - length(replace(v_def, $o8$'compare', case when v_conc -> 'first_drifting' is null then null else jsonb_build_object(
          'value', (v_conc #>> '{first_drifting,rank}')::integer,
          -- 🪤 I2 · התווית הדפיסה 'מקום N' והערך הוא אותו N. המספר
          --    נשאר פעם אחת בלבד, בערך, והתווית מסתיימת בשם-המדד.
          'label', 'הגדול הראשון שכן: ' || (v_conc #>> '{first_drifting,company_name}')
                   || ' — שקטה ' || v_lri || (v_conc #>> '{first_drifting,days_since}') || v_pdi
                   || ' ימים מול קצב של ' || v_lri || (v_conc #>> '{first_drifting,cadence}') || v_pdi
                   || ' · מקומו ברשימת המניבים',
          'direction', 'flat') end,$o8$, ''))) <> length($o8$'compare', case when v_conc -> 'first_drifting' is null then null else jsonb_build_object(
          'value', (v_conc #>> '{first_drifting,rank}')::integer,
          -- 🪤 I2 · התווית הדפיסה 'מקום N' והערך הוא אותו N. המספר
          --    נשאר פעם אחת בלבד, בערך, והתווית מסתיימת בשם-המדד.
          'label', 'הגדול הראשון שכן: ' || (v_conc #>> '{first_drifting,company_name}')
                   || ' — שקטה ' || v_lri || (v_conc #>> '{first_drifting,days_since}') || v_pdi
                   || ' ימים מול קצב של ' || v_lri || (v_conc #>> '{first_drifting,cadence}') || v_pdi
                   || ' · מקומו ברשימת המניבים',
          'direction', 'flat') end,$o8$) then
    raise exception 'm11 text report_m19_customers_overview #8: not exactly once'; end if;
  v_def := replace(v_def, $o8$'compare', case when v_conc -> 'first_drifting' is null then null else jsonb_build_object(
          'value', (v_conc #>> '{first_drifting,rank}')::integer,
          -- 🪤 I2 · התווית הדפיסה 'מקום N' והערך הוא אותו N. המספר
          --    נשאר פעם אחת בלבד, בערך, והתווית מסתיימת בשם-המדד.
          'label', 'הגדול הראשון שכן: ' || (v_conc #>> '{first_drifting,company_name}')
                   || ' — שקטה ' || v_lri || (v_conc #>> '{first_drifting,days_since}') || v_pdi
                   || ' ימים מול קצב של ' || v_lri || (v_conc #>> '{first_drifting,cadence}') || v_pdi
                   || ' · מקומו ברשימת המניבים',
          'direction', 'flat') end,$o8$, $n8$'compare', null,$n8$);
  if (length(v_def) - length(replace(v_def, $o9$'label', 'קצב-התשלום תלוי בסוג הלקוח',$o9$, ''))) <> length($o9$'label', 'קצב-התשלום תלוי בסוג הלקוח',$o9$) then
    raise exception 'm11 text report_m19_customers_overview #9: not exactly once'; end if;
  v_def := replace(v_def, $o9$'label', 'קצב-התשלום תלוי בסוג הלקוח',$o9$, $n9$'label', 'ימים לתשלום, הסוג האיטי',$n9$);
  if (length(v_def) - length(replace(v_def, $o10$'sub', 'חציון ימים מחשבונית לתשלום, לפי סוג הלקוח',$o10$, ''))) <> length($o10$'sub', 'חציון ימים מחשבונית לתשלום, לפי סוג הלקוח',$o10$) then
    raise exception 'm11 text report_m19_customers_overview #10: not exactly once'; end if;
  v_def := replace(v_def, $o10$'sub', 'חציון ימים מחשבונית לתשלום, לפי סוג הלקוח',$o10$, $n10$'sub', 'חציון · ' || v_lri || to_char(v_pay_n, 'FM999,999') || v_pdi || ' חשבוניות',$n10$);
  execute v_def;
end $m11$;

-- ═══ report_m21_drifting — 5 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m21_drifting';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'label', 'לפני חודש (' || v_lri || to_char(v_prev, 'DD/MM/YYYY') || v_pdi || ')',$o0$, ''))) <> length($o0$'label', 'לפני חודש (' || v_lri || to_char(v_prev, 'DD/MM/YYYY') || v_pdi || ')',$o0$) then
    raise exception 'm11 text report_m21_drifting #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'label', 'לפני חודש (' || v_lri || to_char(v_prev, 'DD/MM/YYYY') || v_pdi || ')',$o0$, $n0$'label', 'לפני חודש',$n0$);
  if (length(v_def) - length(replace(v_def, $o1$'label', 'הכנסת 12 החודשים של הלקוחות המסומנים',$o1$, ''))) <> length($o1$'label', 'הכנסת 12 החודשים של הלקוחות המסומנים',$o1$) then
    raise exception 'm11 text report_m21_drifting #1: not exactly once'; end if;
  v_def := replace(v_def, $o1$'label', 'הכנסת 12 החודשים של הלקוחות המסומנים',$o1$, $n1$'label', 'הכנסת הלקוחות המסומנים',$n1$);
  if (length(v_def) - length(replace(v_def, $o2$'label', 'כלל ' || v_lri || coalesce(v_dormant::text, '—') || v_pdi
                   || ' הימים לבדו מוצא ' || v_lri || to_char(v_dorm_n, 'FM999,999,999') || v_pdi
                   || ' לקוחות, ואת אלה הוא מפספס',$o2$, ''))) <> length($o2$'label', 'כלל ' || v_lri || coalesce(v_dormant::text, '—') || v_pdi
                   || ' הימים לבדו מוצא ' || v_lri || to_char(v_dorm_n, 'FM999,999,999') || v_pdi
                   || ' לקוחות, ואת אלה הוא מפספס',$o2$) then
    raise exception 'm11 text report_m21_drifting #2: not exactly once'; end if;
  v_def := replace(v_def, $o2$'label', 'כלל ' || v_lri || coalesce(v_dormant::text, '—') || v_pdi
                   || ' הימים לבדו מוצא ' || v_lri || to_char(v_dorm_n, 'FM999,999,999') || v_pdi
                   || ' לקוחות, ואת אלה הוא מפספס',$o2$, $n2$'label', 'כלל «רדום» מוצא',$n2$);
  if (length(v_def) - length(replace(v_def, $o3$'label', 'הוותיק שברשימה',
        'value', v_oldest ->> 'company_name',
        'format', 'text',$o3$, ''))) <> length($o3$'label', 'הוותיק שברשימה',
        'value', v_oldest ->> 'company_name',
        'format', 'text',$o3$) then
    raise exception 'm11 text report_m21_drifting #3: not exactly once'; end if;
  v_def := replace(v_def, $o3$'label', 'הוותיק שברשימה',
        'value', v_oldest ->> 'company_name',
        'format', 'text',$o3$, $n3$'label', 'הוותיק ברשימה',
        'value', (v_oldest ->> 'days_since')::integer,
        'format', 'days',$n3$);
  if (length(v_def) - length(replace(v_def, $o4$'sub', case when v_oldest is null then 'אין לקוח מתרחק כרגע'
          else v_lri || to_char((v_oldest ->> 'days_since')::integer, 'FM999,999,999') || v_pdi || ' ימים מאז האירוע האחרון — פי '
               || v_lri || (v_oldest ->> 'ratio') || v_pdi || ' מהקצב שלו ('
               || v_lri || (v_oldest ->> 'cadence') || v_pdi || ' ימים)' end,$o4$, ''))) <> length($o4$'sub', case when v_oldest is null then 'אין לקוח מתרחק כרגע'
          else v_lri || to_char((v_oldest ->> 'days_since')::integer, 'FM999,999,999') || v_pdi || ' ימים מאז האירוע האחרון — פי '
               || v_lri || (v_oldest ->> 'ratio') || v_pdi || ' מהקצב שלו ('
               || v_lri || (v_oldest ->> 'cadence') || v_pdi || ' ימים)' end,$o4$) then
    raise exception 'm11 text report_m21_drifting #4: not exactly once'; end if;
  v_def := replace(v_def, $o4$'sub', case when v_oldest is null then 'אין לקוח מתרחק כרגע'
          else v_lri || to_char((v_oldest ->> 'days_since')::integer, 'FM999,999,999') || v_pdi || ' ימים מאז האירוע האחרון — פי '
               || v_lri || (v_oldest ->> 'ratio') || v_pdi || ' מהקצב שלו ('
               || v_lri || (v_oldest ->> 'cadence') || v_pdi || ' ימים)' end,$o4$, $n4$'sub', case when v_oldest is null then 'אין לקוח מתרחק כרגע'
          else v_oldest ->> 'company_name' end,$n4$);
  execute v_def;
end $m11$;

-- ═══ report_m22_notes — 3 replacements ═══
do $m11$
declare
  v_oid oid;
  v_def text;
begin
  select p.oid into strict v_oid from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'report_m22_notes';
  v_def := pg_get_functiondef(v_oid);
  if (length(v_def) - length(replace(v_def, $o0$'label', 'מהן שייכות למשוב שתויג "אחר"',$o0$, ''))) <> length($o0$'label', 'מהן שייכות למשוב שתויג "אחר"',$o0$) then
    raise exception 'm11 text report_m22_notes #0: not exactly once'; end if;
  v_def := replace(v_def, $o0$'label', 'מהן שייכות למשוב שתויג "אחר"',$o0$, $n0$'label', 'הערות על «אחר»',$n0$);
  if (length(v_def) - length(replace(v_def, $o1$'window', 'כל הזמנים · נכון ל-' || v_lri || to_char(v_today, 'DD/MM') || v_pdi,
        'compare', jsonb_build_object(
          'value', coalesce(v_other_yr_txt, '—'),
          'label', 'פילוח לפי שנה (השנה הנוכחית חלקית)', 'direction', 'flat'),$o1$, ''))) <> length($o1$'window', 'כל הזמנים · נכון ל-' || v_lri || to_char(v_today, 'DD/MM') || v_pdi,
        'compare', jsonb_build_object(
          'value', coalesce(v_other_yr_txt, '—'),
          'label', 'פילוח לפי שנה (השנה הנוכחית חלקית)', 'direction', 'flat'),$o1$) then
    raise exception 'm11 text report_m22_notes #1: not exactly once'; end if;
  v_def := replace(v_def, $o1$'window', 'כל הזמנים · נכון ל-' || v_lri || to_char(v_today, 'DD/MM') || v_pdi,
        'compare', jsonb_build_object(
          'value', coalesce(v_other_yr_txt, '—'),
          'label', 'פילוח לפי שנה (השנה הנוכחית חלקית)', 'direction', 'flat'),$o1$, $n1$'window', 'כל הזמנים · לפי שנה (השנה הנוכחית חלקית): ' || coalesce(v_other_yr_txt, '—'),
        'compare', null,$n1$);
  if (length(v_def) - length(replace(v_def, $o2$'title', 'מטריצת ההסכמה · מה הלקוח תייג מול מה המודל מצא · מתוך '$o2$, ''))) <> length($o2$'title', 'מטריצת ההסכמה · מה הלקוח תייג מול מה המודל מצא · מתוך '$o2$) then
    raise exception 'm11 text report_m22_notes #2: not exactly once'; end if;
  v_def := replace(v_def, $o2$'title', 'מטריצת ההסכמה · מה הלקוח תייג מול מה המודל מצא · מתוך '$o2$, $n2$'title', 'תגית הלקוח מול המודל · '$n2$);
  execute v_def;
end $m11$;
